```{r}
library(tidyverse)
library(lubridate)
library(baseballr)
library(glue)
```

```{r}

# get all pitches in 2022
# swing_data <-
#   read_csv("~/Downloads/savant_data-21.csv")

get_statcast_data <- function(date) {
  statcast_search(start_date = date, end_date = date, player_type = "batter")
}

# read in previously acquired data

filename <- "swing_data_2022.rds"

old_data <- readRDS(filename)

# set start_date to the most recent date in the data file
start_date <-
  as.Date(
    swing_data %>%
      filter(game_date == max(game_date)) %>%
      distinct(game_date) %>%
      pull()
  )

# if needed, append new swing data to the dataset. always ensure swing_data
# is the output variable name
if (start_date != Sys.Date() - 1) {

  # get new data
  new_data <-
    seq.Date(start_date, Sys.Date() - 1, by = "day") %>%
    map_df(get_statcast_data)

  # append to old data
  swing_data <- bind_rows(old_data, new_data) %>%
    arrange(game_date)

  # save updated dataset to disk for later usage
  saveRDS(swing_data, filename)
} else {
  swing_data <- old_data
  remove(old_data) # no longer needed
}

# set minimum number of pitched as the median
min_pitches <-
  swing_data %>%
  count(player_name) %>%
  summarize(q = quantile(n, .5)) %>%
  as.numeric() %>%
  ceiling()

# compute scale factors for later computing MAD

coords <-
  swing_data %>%
  group_by(player_name) %>%
  filter(
    n() >= min_pitches,
    description %in% c(
      "hit_into_play", "foul", "swinging_strike",
      "foul_tip", "swinging_strike_blocked"
    )
  ) %>%
  ungroup() %>%
  select(plate_x, plate_z)

const_horiz <- sd(coords$plate_x, na.rm = TRUE) / mad(coords$plate_x, na.rm = TRUE, constant = 1)
const_vert <- sd(coords$plate_z, na.rm = TRUE) / mad(coords$plate_z, na.rm = TRUE, constant = 1)

# for each player, compute the median absolute deviation in both axes, number of swings, and total plate coverage

swing_grouped <-
  swing_data %>%
  group_by(player_name) %>%
  filter(n() >= min_pitches) %>%
  # compute the p95 for the tops and bottoms of players' strike zones
  mutate(
    p95_sz_bot = quantile(sz_bot, .95, na.rm = TRUE),
    p95_sz_top = quantile(sz_top, .95, na.rm = TRUE),
    zone_height = p95_sz_top - p95_sz_bot,
    center_z = (p95_sz_bot + p95_sz_top) / 2
  ) %>% # vertical center of the zone depends on zone height
  # retain swings only
  filter(description %in% c(
    "hit_into_play", "foul", "swinging_strike",
    "foul_tip", "swinging_strike_blocked"
  )) %>%
  # show MAD of swing coordinates, centering on most common strike zones
  group_by(player_name, zone_height) %>%
  summarize(
    mad_x = mad(plate_x, center = 0, na.rm = TRUE, constant = const_horiz), # horiz. center of zone is always coord. 0
    mad_z = mad(plate_z, center = center_z, na.rm = TRUE, constant = const_vert),
    num_swings = n()
  ) %>%
  mutate(plate_cov = mad_x * mad_z / zone_height) %>%
  ungroup()

most_aggressive <-
  swing_grouped %>%
  arrange(desc(plate_cov)) %>%
  filter(row_number() <= 10)

least_aggressive <-
  swing_grouped %>%
  arrange(plate_cov) %>%
  filter(row_number() <= 10)


swing_data %>%
  filter(player_name %in% most_aggressive$player_name) %>%
  # prevent drawing multiple strike zone rectangles on screen by computing mean strike zone boundaries
  group_by(player_name) %>%
  mutate(
    p95_sz_bot = quantile(sz_bot, .95, na.rm = TRUE),
    p95_sz_top = quantile(sz_top, .95, na.rm = TRUE),
  ) %>%
  ggplot(aes(plate_x, plate_z)) +
  geom_point(alpha = 0.3) +
  geom_density_2d_filled(alpha = 0.7) +
  geom_density_2d(alpha = 0.1) +
  geom_rect(aes(xmin = -.708, xmax = .708, ymin = p95_sz_bot, ymax = p95_sz_top), color = "grey", fill = NA, lty = "dashed") +
  facet_wrap(vars(player_name), ncol = 5) +
  ylim(0, 5) +
  xlim(-2, 2) +
  ggtitle("Free Swingers, 2022", subtitle = "Batters with the largest 'swing zones' relative to their height. One point = one swing") +
  labs(x = "Pitch Horizontal Location (ft)", y = "Pitch Height (ft)", caption = glue("Source: Baseball Savant through {Sys.Date() - days(1)}. Min {min_pitches} pitches seen")) +
  theme(legend.position = "none")


ggsave("free-swingers.png", height = 8, width = 15)

swing_data %>%
  filter(player_name %in% least_aggressive$player_name) %>%
  group_by(player_name) %>%
  mutate(
    p95_sz_bot = quantile(sz_bot, .95, na.rm = TRUE),
    p95_sz_top = quantile(sz_top, .95, na.rm = TRUE),
  ) %>%
  ggplot(aes(plate_x, plate_z)) +
  geom_point(alpha = 0.3) +
  geom_density_2d_filled(alpha = 0.7) +
  geom_density_2d(alpha = 0.1) +
  geom_rect(aes(xmin = -.708, xmax = .708, ymin = p95_sz_bot, ymax = p95_sz_top), color = "grey", fill = NA, lty = "dashed") +
  facet_wrap(vars(player_name), ncol = 5) +
  ylim(0, 5) +
  xlim(-2, 2) +
  ggtitle("Selective Hitters, 2022", subtitle = "Batters with the smallest 'swing zones' relative to their height. One point = one swing") +
  labs(x = "Pitch Horizontal Location (ft)", y = "Pitch Height (ft)", caption = glue("Source: Baseball Savant through {Sys.Date() - days(1)}. Min {min_pitches} pitches seen")) +
  theme(legend.position = "none")

ggsave("patient-swingers.png", height = 8, width = 15)
```
