
```{r}

fg_db <- dplyr::src_mysql(dbname = Sys.getenv("FG_DB"), 
                            host = Sys.getenv("FG_HOST"), 
                            user = Sys.getenv("FG_USER"),
                            password = Sys.getenv("FG_PW"))


```

### Batters -- biggest increase in contact% from 2016 - 2017?

```{r}

batter_info <- fg_db %>%
  tbl("player_info") %>%
  select(PlayerId, FirstName, LastName) %>%
  collect(n=Inf)

batting_data <- fg_db %>%
  tbl("stats_batting_master") %>%
  filter(Season >= 2015,
         Type == 0) %>%
  select(playerid, PA, Season, `Contact%`) %>%
  collect(n=Inf)
```

```{r}
full_data <- inner_join(batter_info, batting_data, by=c("PlayerId" = "playerid")) %>%
  mutate(Name = sprintf("%s %s", FirstName, LastName)) %>%
  group_by(Season) %>%
  mutate(lg_contact = mean(`Contact%`, na.rm = TRUE)) %>%
  ungroup() %>%
  mutate(contact_plus = round(100 * (`Contact%` / lg_contact )), 0) %>%
  select(Name, Season, PA, contact_plus)

full_data
```

```{r}
contact_plt_data <- full_data %>%
  group_by(Name) %>%
  arrange(Season) %>%
  mutate(contact_diff_since_2015 = contact_plus - lag(contact_plus, 1)) %>%
  filter(Season == 2017,
         PA >= 30) %>%
  arrange(desc(contact_diff_since_2015))

contact_plt_data
```