```{r}

fg_players <- fg_db %>%
  tbl("player_info") %>%
  collect(n=Inf)

fg_pitch <- fg_db %>%
  tbl("stats_pitching_master_pfx") %>%
  filter(Type == 0) %>%
  collect(n=Inf)


fg_bat <- fg_db %>%
  tbl("stats_batting_master_pfx") %>%
  filter(Type == 0) %>%     #get only full-season stats for each player
  collect(n=Inf)



```


```{r}

fg_batters <- inner_join(fg_players, fg_bat, by=c("PlayerId" = "playerid")) %>%
  filter(Position != "P",             #don't get batting WAR for pitchers
         BISPosition != "SP",
         BISPosition != "RP") %>%
  mutate(Name = sprintf("%s %s", FirstName, LastName)) %>%
  select(PlayerId, Name, Season, PA, ValueW, oswing = `pfxO-Swing%`, zswing=`pfxZ-Swing%`)

batters_disc <- fg_batters %>%
  group_by(Season) %>%
  summarize(mean_oswing = mean(oswing, na.rm = TRUE),
            mean_zswing = mean(zswing, na.rm = TRUE)) %>%
  
  arrange(Season)

ggplot(batters_disc, aes(Season, mean_oswing)) + geom_bar(stat="identity")
```

```{r}
fg_pitchers <- inner_join(fg_players, fg_pitch, by="PlayerId") %>%
  filter(BISPosition %in% c("SP", "RP")) %>% #don't get pitching WAR for position players
  mutate(Name = sprintf("%s %s", FirstName, LastName),
         ozone = 1 - `pfxZone%`) %>%
  select(PlayerId, Name, Season, TBF, ValueW, BISPosition, oswing = `pfxO-Swing%`, ozone, zswing=`pfxZ-Swing%`)




fool <- fg_pitchers %>%
  group_by(Season) %>%
  mutate(lg_oswing = mean(oswing),
         lg_ozone = mean(ozone)) %>%
  ungroup() %>%
  mutate(oswing_plus = round(100 * (oswing / lg_oswing),0),
         ozone_plus = round(100 * (ozone / lg_ozone),0),
         fool = round(100 * (oswing_plus / ozone_plus), 0),
         prob_both = oswing * ozone) %>%
  filter(Season == 2016) %>%
  select(Name, Season, BISPosition, TBF, oswing_plus, ozone_plus, fool)

fool_rp <- fool %>%
  filter(Season == 2016,
         BISPosition == "RP",
         TBF >= 200) %>%
  select(-BISPosition, -Season) %>%
  arrange(desc(fool))

fool_sp <- fool %>%
  filter(Season == 2016,
         BISPosition == "SP",
         TBF >= 400) %>%
  select(-BISPosition, -Season) %>%
  arrange(desc(fool))



# fool_plt <- fool %>%
#   filter(Season == 2016) %>%
#   ggplot(aes(ozone_plus, oswing_plus)) + geom_point()
# 
# fool_plt




```

```{r}

pitchers_2016 <- fg_pitchers %>%
  filter(Season == 2016) %>%
  filter(TBF >= 300) %>%
  arrange(desc(ozone))

batters_2016 <- fg_batters %>%
  filter(Season == 2016) %>%
  filter(PA >= 300) %>%
  arrange(desc(oswing))
```