---
title: "jimenez"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




Ubaldo Jimenez has always had mechanics that are sometimes referred to as "funky". When he was throwing 97 MPH heat, this didn't matter much. But as his fastball 

This is an industry term intended to mean "unpredictable" and "hard to control" but which colloquially means just "weird-looking". Six years ago when he was throwing 97 MPH heat, batters couldn't touch him. He threw a no-hitter that year. But But as his fastball velocity slowed to 90-92 MPH, hitters began timing his fastball more easily and laying off pitches out of the zone. The resulting spike in walk rate has, at times, gotten Jimenez demoted to the bullpen.

Coordinating your entire body's muscular system in such a way so as to throw a ball 90 MPH at a small target sixty feet and six inches away while someone tries to hit it with a bat is not something I can do. The people who can do this over and over again get paid millions of dollars.  

was bad to start the year. Was demoted to the bullpen twice and recalled only because of Tillman's injury.


==

Headline: Ubaldo Jimenez Found His Mechanics at the Right Time


With his Orioles clinging to a Wild Card spot and still within reach of a division title, Ubaldo Jimenez picked a great time to throw four good starts in place of an injured Chris Tillman. The words "Ubaldo Jimenez" and "good start" haven't appeared together often this year. In fact the word "start" itself couldn't always apply; when Tillman hit the DL, Jimenez was in the bullpen. 

Jimenez's first two years with the Orioles contrasted greatly. In 2014 he walked nearly 14% of his batters en route to a 4.48 xFIP. Although the Orioles won the AL East and took Jimenez to the ALDS, they left him off the ALCS roster. But in 2015 Jimenez harnessed his funky mechanics, got more ground balls and walked fewer batters, and had a good 3.83 xFIP.

So far this year's been more of 2014 than 2015. Although he's walking fewer batters than 2014, he's striking out fewer too, leading to a lower K-BB%. Everyone noticed. After beginning the season as the team's fifth starter, here's what happened:

-Was temporarily demoted to the bullpen on June 14th. At the time his K- rate (K rate relative to league average (K%-) was 85. More importanly BB%- rate was an atrocious 148.
  -Made a 2.1 inning relief appearance on June 17th, in an emergency relief of Mike Wright. Jimenez Struck out four batters, but walked two and gave up two longballs.
  -Returned to rotation to start against the Padres on June 22nd.
  -Remained in rotation until getting demoted again on August 1st. [http://www.cbssports.com/fantasy/baseball/news/orioles-ubaldo-jimenez-bumped-from-rotation/]. During this period his K%- was a much-better 111. However his BB%- deteriorated further, spiking to 204. He couldn't stop issuing free passes to batters. 
  -Made three relief appearances; did not pitch especially well. 
  -Returned to the rotation on August 24th, as a result of Chris Tillman going on the DL [[http://camdendepot.blogspot.com/2016/08/ubaldo-jimenez-is-back-in-rotation-for.html].]. At the time the Orioles were 69-56, two games back in the AL East Division and two games ahead of Seattle for the second Wild Card spot.

His four starts in place of Tillman were good. Jimenez cut his walk rate by two-thirds while still striking out more batters than average. He also threw the team's first complete game since 2014.

A sample size of four games isn't large, but when dealing with strikeout and walk rates, it's enough to take notice. The following graph shows the trend:

[graph] 

In an interview with Eduardo A. Encina of the Baltimore Sun [http://www.baltimoresun.com/sports/orioles/bs-sp-orioles-jimenez-0909-20160908-story.html], Jimenez acknowledges he'd lost control of his delivery. He credits pitching coach Dave Wallace, bullpen coach Dom Chiti, and special pitching instructor Ramon Martinez (Pedro's brother) with rediscovering a motion that helped him in these recent starts. Specifically, after breaking his hands, he's simply lowering his arm instead of extending it backwards.

It can seem odd that such a small change in one piece of the delivery separates success from failure. But when all the body's muscles are involved, no change is minor. I don't know much about pitching mechanics, but I do know about compound lifts like squats and deadlifts. The activities are similar in that success comes when you repeatedly recruit specific muscles in a specific sequence.  If one link in that chain is off, the process breaks down to some degree. You may still luck into a swinging strike, an infield fly, or successfully lifting the weight. But you may not be so lucky next time.

To be sure, Jimenez will lose his mechanics again. He always does. In a Sports on Earth article entitled "Ubaldo Jimenez searches for his lost mechanics [[http://www.sportsonearth.com/article/43634906/]" from 2013, he talks about having lost them for two full years. Here's a discussion from 2014 [http://articles.baltimoresun.com/2014-04-19/sports/bal-baltimore-orioles-righthander-ubaldo-jimenez-working-on-more-aggressive-mechanics-20140419_1_mechanics-dom-chiti-orioles] about the same issue. And one from 2015 [http://m.mlb.com/news/article/109930788/orioles-right-hander-ubaldo-jimenez-looking-for-success-with-simplified-delivery/].  


Ubaldo's mental state also comes into play. For him, the mind and the body may be connected moreso than for other pitchers. The Sports on Earth article talks about how Ubaldo thinks too much on the mound. Ubaldo himself mentions that the years 2011-2012 were "heartbreaking". The Orioles television broadcasters often talk about how badly Ubaldo feels when he pitches poorly. 

As they head into the final weeks of the season, the Orioles sure hope Jimenez's recent changes stick. Their other rotation options leave something to be desired. Behind Kevin Gausman, who's having a good year, the team relies on:

- Chris Tillman, who returned Sunday from the DL. He was having a good year, albeit one built on a very high LOB%, before going down with shoulder discomfort.
- Dylan Bundy, who's been good in the rotation but who is a young Tommy John recoveree well above his career-high in innings pitched. Given the expectations heaped upon him by the fanbase, no one is even sure how long he'll stay in the rotation.
- Wade Miley, who's pitched well since joining the team but who's has fallen victim to a very low LOB% and a very high HR/FB rate.
- Yovani Gallardo, whose 5.38 xFIP says all you need to know about his 5.44 ERA.

Collectively, this group and others have put together a 107 xFIP-, easily the worst among all the playoff hopefuls save Texas.



[[conclusion]]


===

If the weightlifting analogy doesn't work for you, think of the last time you banged your bare toe into a piece of furniture. Didn't you limp around for awhile, trying not to walk on the toe? Didn't that throw off your whole gait? Could you have run a marathon in that condition? Perhaps, but the results would not be optimal.

It can also seem odd that it takes three people to help a veteran pitcher figure out his delivery. But isolating just anyone's mechanics is difficult. Starters work only every fifth day, which limits the opportunities to see whether an adjustment has an impact And they start against different batters each time, who are making their own adjustments. Not to mention weather and park factors coming into the mix. Now consider you have a different home plate umpire and perhaps different defenders.













Pitching is harder in the sense that you need to deceive the hitter about where the ball is going and when. With squats, the weight doesn't care about what's happening. 




If you fail to master your pitching mechanics, you'll miss your target, perhaps widely enough to not encourage the hitter to swing. This is what happens when Ubaldo is off. It's why his O-Swing% is consistently below the league average.  


do this while pitching, so in pitching, you'll miss your target. Six years ago Jimenez was throwing 97 MPH heat, so missing his target wasn't a big deal.  



it takes a team of three people to help a veteran pitcher keep his mechanics on track. But Jimenez has always been special in that regard. He acknowledged that even in the minor leagues, 

I don't know a lot about pitching mechanics, but I do know about compound body movements. During heavy weightlifting you have to maintain tight control and timing over how and when your muscles fire in sequence. Otherwise, you'll lose control of the weight. In an isolation exercise, this only means you're failing to isolate the muscle, But in a compound lift like a squat or deadlift, your lower back comes into play, which is how people end up with herniated discs.

Ji

When this happens your body will recruit other muscles to keep the weight in motion, muscles that probably aren't designed to handle the load. If you fail a bicep curl, you'll feel yourself naturally start to swing your hips forward or shoulder back to get under the weight or help push it up. 

If you fail a squate Either that or you'll drop the weight. 
  
  ===


delivered four good starts. He wasn't just lucky; he cut his sky-high walk rate by two-thirds while maintaining a good strikeout rate.

He claims to have regained control of his mechanics [http://www.baltimoresun.com/sports/orioles/bs-sp-orioles-jimenez-0909-20160908-story.html]. He's said that before 

The team needs Jimenez to continue pitching well. Their other rotation options aren't that great.


===

The team demoted him to the bullpen after a terrible start to the year. At the time he'd struck out out only 17.3% of batters while walking an inordinate 11.4% of them.

He served in emergency relief for one game [http://www.fangraphs.com/wins.aspx?date=2016-06-17&team=Orioles&dh=0], striking out four in 2.1 innings but walking two and surrendering two long balls. He made his next start on June 22nd and stayed there. The good news is he struck out 22.5% of batters. The bad news? His walk rate was an unsalvageable 15.7%, more than twice league-average.

That performance got him a ticket back to the bullpen on August 1st. He was not especially effective, maintaining a K rate of 20.7% but also a horrendous walk rate of 17.1% in three appearances. He returned to the starting rotation on August 24th only because nominal ace Chris Tillman hit the disabled list [http://www.mlbtraderumors.com/2016/08/chris-tillman-disabled-list-orioles.html].

But since then, he's made four good starts. His walk rate tumbled to just 5.6%, keeping both him and the Orioles in games longer. On September 5th he pitched the team's first complete game since 2014. He was so good that pundits started questioning whether the team could use a six-man rotation now that Chris Tillman is back from the DL. [http://www.csnmidatlantic.com/baltimore-orioles/showalter-doesnt-rule-out-six-man-rotation-when-chris-tillman-returns] ---- NEED TO UPDATE MONDAY OR TUESDAY TO SEE IF JIMENEZ IS SCHEDULED TO START AGAIN.

[table]

In graph form:

http://www.fangraphs.com/graphs.aspx?playerid=3374&legend=1,2&statArr=120,121&split=base&time=game&ymin=&ymax=&start=2016&end=2016&rtype=single&gt1=3


[mechanics fix?]

The Orioles need Jimenez to pitch well. As Craig noted last week [http://www.fangraphs.com/blogs/the-case-for-manny-machado-for-american-league-mvp/], every game the team plays is meaningful. They are [in what position in division / WC?] after [recent results?].

Besides Kevin Gausman, who's having a legitimately good season, the team has:


Two other rotation experiements this year, Mike Wright and Tyler Wilson, were demoted to Triple-A. The team also DFA'd rotation candidate Odrisamer Despaigne.






what else can I write about?????? mechanics fix maybe???








terrible early in the year, getting demoted to the bullpen in mid-June on the back of striking out 15% fewer batters than league starters while walking 48% more.

He wasn't much help upon returning in late June, striking out more batters but walking an incredible 15.7% of them. Those poor starts buried him for good, at least until nominal team ace Chris Tillman went on the DL with a shoulder injury. 

[graph or timeline or something]





After pitching ineffectively for much of the year, and getting demoted to the bullpen twice because of it, ineffectiveness and injuries in the Orioles' already-weak rotation forced him back on the mound in late August. He's pitched well in four starts since returning to the rotation. As a result the Orioles 

-The Orioles are in a precarious playoff spot. As Craig showed last week [ [http://camdendepot.blogspot.com/2016/08/ubaldo-jimenez-is-back-in-rotation-for.html]. ], every game the Orioles play is fraught with meaning. Part of the reason is their opposition has been playing much better lately. But part of the reason is that their starting rotation  

-Jimenez had a scarily bad year in 2014, yet the Orioles won the AL East division title.
-Jimenez pitched much better in 2015. (link to CD article or talk about why)
-This year he started off terribly, twice getting demoted to the bullpen. But his replacements have proven ineffective (Mike Wright, Tyler Wilson, and to some extent Wade Miley)

Timeline:

  
  
  In four starts since then, his K%- remains better-than-average at 106. His walk rate though has tumbled to a very-helpful 73.
  
  
  
  
  -In four starts since then:
  107 BF
  23 K (21.4% rate)
  6 BB (5.6% rate)
  
    
  
  
  
-But then Chris Tillman went on the DL
-The Orioles needed a solid starter after burning through Despaigne, etc. for awhile.
-So Jimenez was promoted again, charged with helping the Orioles remain in the playoff race
.And His results have been very good:
-When I look at Jimenez I see an incredibly low LOB%, second-lowest among pitchers with at least 120 IP.
-So some regression to the mean was bound to occur.
-But the fact he was walking so many batters set him up to fail. His walk rate started off poor, at 10.9% in April. It was at 12.8% in June and July before peaking at 14.6% in August.


-Extremely low LOB% - among pitchers with at least 120 it's second-worst, at 62.2%
-Jimenez isn't doing himself any favors by walking 
  
