---
title: "manager-analysis"
output: html_document
---



```{r}
# library(tidyverse)
library(dplyr)
library(tidyr)
library(broom)
library(stringr)
library(RMySQL)
library(lubridate)
library(plotly)
library(glue)
library(styler)

fgt <- theme(
  panel.background = element_rect(color = "lightgrey", fill = "white"),
  axis.title = element_text(family = "Lato"),
  axis.text = element_text(family = "Lato"),
  legend.title = element_text(family = "Lato"),
  legend.text = element_text(family = "Lato"),
  legend.background = element_rect(fill = "white"),
  legend.key = element_rect(fill = "white"),
  plot.title = element_text(family = "Lato"),
  panel.grid.major = element_line(size = .1, color = "lightgrey"),
  panel.grid.minor = element_line(size = 0),
  # strip.background = element_rect(fill = "#50ae26"),
  strip.text = element_text(family = "Lato")
)

fg_db <- dplyr::src_mysql(
  dbname = Sys.getenv("FG_DB"),
  host = Sys.getenv("FG_HOST"),
  user = Sys.getenv("FG_USER"),
  password = Sys.getenv("FG_PW")
)

TWILIO_SID <- Sys.getenv("TWILIO_SID")
TWILIO_TOKEN <- Sys.getenv("TWILIO_TOKEN")
twilio_number <- Sys.getenv("twilio_number")

send_message <- function(msg) {
  tw_send_message(from = twilio_number, to = "5123505107", body = msg)
}
```


- quantify good bullpen decisions by correlating k-bb% for the first 3 months of the season with average gmLI for the second half of the season

get data

```{r}

players <- fg_db %>%
  tbl("player_info") %>%
  filter(BISPosition == "RP") %>%
  dplyr::select(playerid = PlayerId, FirstName, LastName) %>%
  collect(n = Inf) %>%
  unite(player_name, FirstName, LastName, sep = " ")

teams <-
  fg_db %>%
  tbl("season_team") %>%
  dplyr::select(Season, TeamId, AbbName) %>%
  collect(n = Inf)


# get k-bb% for pitchers who faced at least 25 batters in the first half, computed relative to the other pitchers on their team
# who faced at least 25 batters. this is a way to get the manager's options for whom to put into a game
reliever_perf2 <-
  fg_db %>%
  tbl("wpa_daily_pitching") %>%
 # filter(GameDate >= "2008-01-01") %>%
  dplyr::select(GameDate, PlayerId, TeamId, SO, BB, TBF) %>%
  collect(n=Inf) %>%
  mutate(Season = year(GameDate),
         month = month(GameDate)) %>%
  filter(month %in% c(3, 4, 5, 6)) %>%
  group_by(Season, PlayerId, TeamId) %>%
  filter(sum(TBF) >= 25) %>%
  summarize(k_perc = sum(SO) / sum(TBF),
            bb_perc = sum(BB) / sum(TBF)) %>%
  mutate(first_half_K_BB_perc = round((k_perc - bb_perc) * 100, 1)) %>%
  group_by(Season, TeamId) %>%
  mutate(first_half_K_BB_perc_plus = round(first_half_K_BB_perc / mean(first_half_K_BB_perc) * 100, 0))


# get plate appearances that began with a pitcher who was subbed in for another pitcher
wpa_data <- fg_db %>%
  tbl("wpa_log") %>%
  filter(!is.na(PitcherSubId)) %>%
  collect(n = Inf)
```

K-BB%+ for 1st Half vs. gmLI for second half

```{r}



# TODO: how to handle relievers who switched teams mid-season? 2008 Nick Masset is an example. he shows up with both CWS and CIN
# 2018 Zach Britton is another example. he should not get a data point with 2018 BAL, but he has one.
# maybe remove them, as doing this will keep the manager constant
# TODO: speaking of managers: can we hold them constant as well? avoid teams who switched managers mid-season?


# get the average LI when entering a game, for pitchers in the 2nd half of the season July thru September
li_individual <-
  wpa_data %>%
  inner_join(players, by = c("P" = "playerid")) %>%
  mutate(Season = year(GameDate),
         game_month = month(GameDate)) %>%
  filter(game_month %in% c(7, 8, 9)) %>%
  inner_join(teams, by = c("Season",
    "HomeTeamId" = "TeamId"
  )) %>%
  mutate(home_team = AbbName) %>%
  inner_join(teams, by = c("Season",
    "AwayTeamId" = "TeamId"
  )) %>%
  mutate(
    away_team = AbbName.y,
    inning_half = if_else(InningHalf == 0, "Top", "Bottom"),
    pitching_team = if_else(inning_half == "Top", home_team, away_team),
    pitching_team_score = if_else(inning_half == "Top", HomeScore, AwayScore),
    batting_team_score = if_else(inning_half == "Bottom", HomeScore, AwayScore),
    pitching_team_lead = pitching_team_score - batting_team_score
  ) %>%
  dplyr::select(Season, GameDate, game_month, home_team, away_team, inning_half,
    inning = Inning, outs = Outs, pitching_team_score, batting_team_score, pitching_team_lead, pitching_team, pitcher_playerid = P,
    pitcher_subbed_in = player_name, LI
  )

# for season-teams who had at least 5 pitchers appear at least 5 times each in the 2nd half,
# find the mean gmLI for each pitcher and add in first-half K-BB% data
li_grouped <-
  li_individual %>%
  group_by(Season, pitching_team, pitcher_playerid, pitcher_subbed_in) %>%
  summarize(second_half_num_appearances = n(),
            second_half_mean_gmLI = round(mean(LI), 2)) %>%
  inner_join(reliever_perf2, by=c("Season", "pitcher_playerid" = "PlayerId")) %>%  # attach first-half k-bb rates to second-half gmLI stats
  mutate(label = glue("{Season} {pitching_team} - {pitcher_subbed_in}")) %>%
  filter(second_half_num_appearances >= 5) %>%
  group_by(Season, pitching_team) %>%
  filter(n() >= 5)  %>%  # condense to only teams who had 5 relievers who appeared at least 5 times each in the 2nd half
  group_by(Season, pitcher_playerid) %>%
  filter(n() == 1)  # keep only players who played for one team in the season. this filters out guys like 2018 zach britton, who had 7 app for BAL and 25 app
                    # for NYY in the second half

# for each season-team, identify its correlation between first-half K-BB% and second-half gmLI.
# this speaks to managers' rigidity
correlations <-
  li_grouped %>%
#  filter(Season >= 2008) %>%
  unite(season_team, Season, pitching_team, sep = " ") %>%
  split(.$season_team) %>%
  map(~ lm(second_half_mean_gmLI ~ first_half_K_BB_perc_plus, data = .)) %>%
  map(summary) %>%
  map_dbl("r.squared") %>%
  tidy() %>%
  mutate(r_squared = round(x, 2)) %>%
  dplyr::select(names, r_squared) %>%
  arrange(desc(r_squared))

correlations


# 
# split(.$model_type) %>%
#   map(~ lm(vote_share ~ predicted_vote_share, data = .)) %>%
#   map(summary) %>%
#   map_dbl("r.squared") %>%
#   tidy() 


```

```{r, fig.height=3}
reliever_use_plt <-
  ggplot(li_grouped, aes(first_half_K_BB_perc_plus, second_half_mean_gmLI, text = label)) +
  geom_point()

ggplotly(reliever_use_plt, tooltip = c("text", "first_half_K_BB_perc_plus", "second_half_mean_gmLI"))


top_10_names <-
  correlations %>%
  head(10)

bottom_10_names <-
  correlations %>%
  tail(10)

# graph plots of top 10 teams
top_10_plt <-
  li_grouped %>%
  unite(season_team, Season, pitching_team, sep = " ") %>%
  filter(season_team %in% top_10_names$names) %>%
  ggplot(aes(first_half_K_BB_perc_plus, second_half_mean_gmLI, text = pitcher_subbed_in)) +
  geom_point() +
  facet_wrap(vars(season_team), scales = "free_x") +
  ggtitle("Best Bullpen Usage")

bottom_10_plt <-
  li_grouped %>%
  unite(season_team, Season, pitching_team, sep = " ") %>%
  filter(season_team %in% bottom_10_names$names) %>%
  ggplot(aes(first_half_K_BB_perc_plus, second_half_mean_gmLI, text = pitcher_subbed_in)) +
  geom_point() +
  facet_wrap(vars(season_team), scales = "free_x") +
  ggtitle("Worst Bullpen Usage")

ggplotly(top_10_plt, tooltip = c("text", "first_half_K_BB_perc_plus", "second_half_mean_gmLI"))

ggplotly(bottom_10_plt, tooltip = c("text", "first_half_K_BB_perc_plus", "second_half_mean_gmLI"))

# not fair to managers really ... they can't control who's on their roster, so they can't control 

# so like 2011 SFG ... Romo was much better as a pitcher than anyone else in the bullpen. yet Wilson and Affeldt got the highest leverage opportunities. 
# but 2013 MIA didn't have much of a choice ... 

```

