---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(googlesheets4)
library(lubridate)
library(glue)
library(scales)
```

```{r}
meal_data <-
  read_sheet("https://docs.google.com/spreadsheets/d/1RBvCN7sc1CgGTVH9mnHADmJ6OflK0mAFMJGLt60CXog/edit#gid=0") %>%
  filter(!is.na(Main)) %>%
  dplyr::select(meal = Main, last_eaten = `Last Eaten`) %>%
  mutate(meal = tolower(meal),
         last_eaten = ymd(last_eaten),
    month_eaten = floor_date(last_eaten, unit = "month"),
    protein = str_extract(meal, "steak|chicken breast|chicken thigh|chicken|pork|sausage|beef|turkey|bacon|chorizo|fish|tilapia|barbacoa|ribs"),
    side = str_extract(meal, "(w/|with|\\+).*"),
protein = str_replace_all(protein, c("chicken breast" = "chicken",
                             "chicken thigh" = "chicken",
                             "beef" = "ground beef",
                             "ribs" = "pork", 
                             "tilapia" = "fish",
                             "flounder" = "fish",
                             "haddock" = "fish")),
method = str_extract(meal, "ip|instant pot|slow cooker|crock pot|roast|sautee|sous vide")) %>%
  replace_na(list(protein = "none",
                  method = "none specified"))
         
meal_data %>%
  count(month_eaten, protein) %>%
  complete(month_eaten, protein, fill = list(n=0)) %>%
  ggplot(aes(month_eaten, n, fill = protein)) + geom_area()

meal_data %>%
  count(protein, sort = TRUE) %>%
  ggplot(aes(reorder(protein, n), n)) + geom_col() + coord_flip() +
  labs(x="", y = "number of meals made")
  
meal_data %>% 
  count(meal, sort = TRUE)

# how long has it been since i last made each meal?
meal_data %>%
  group_by(meal) %>%
  filter(last_eaten == max(last_eaten)) %>%
  mutate(days_since_cooked = difftime(Sys.Date(), last_eaten, unit = "days")) %>%
  select(meal, last_eaten, days_since_cooked) %>%
  arrange(desc(days_since_cooked))
```


```{r}
# 10 random meals eaten at least 3 months prior
meal_data %>%
  group_by(meal) |>
  filter(last_eaten == max(last_eaten),
         last_eaten <= Sys.Date() - days(90)) %>%
  ungroup() |>
  slice_sample(n=10) %>%
  select(meal, last_eaten)

```


PS5 playtime in 2021 

```{r}
games_played_2021 <-
  tribble(
  ~game, ~hours_played,
  "Mass Effect: Legendary Edition", 5,
  "Guardians of the Galaxy", 19,
  "Star Wars: Squadrons", 167,
  "NieR: Automata GotY Edition", 27,
  "Tales of Arise", 59,
  "Bloodborne + The Old Hunters DLC", 99,
  "Returnal", 5,
  "Dark Souls II: Scholar of the First Sin", 17,
  "Dark Souls: Remastered + Artorias of the Abyss DLC", 33,
  "Demon's Souls", 29,
  "Death Stranding", 70,
  "Astro's Playroom", 2,
  "Resident Evil Village", 17,
  "Resident Evil 7 Biohazard", 13,
  "Genshin Impact", 29,
  "God of War III Remastered", 12,
  "God of War (2018)", 20,
  "Dragon Quest XI", 12,
  "Borderlands: The Handsome Collection", 5,
  "Borderlands: GotY Edition", 17
)

hours_played <- sum(games_played_2021$hours_played)

games_played_2021 %>%
  ggplot(aes(reorder(game, hours_played), hours_played)) +
  geom_col() + coord_flip() +
  ggtitle("PS4/5 Games Played, 2021", subtitle = glue("{hours_played} total hours")) +
  labs(x="", caption = "Source: PS5 Profile")

```


```{r}
balances <-
  read_csv(("~/Documents/transactions2/Sheet 2-Table 1.csv"),
         col_types = list(col_character(), col_character(), col_character(), col_number())) %>%
  select(date = 1, balance = 4) %>%
  filter(balance != "BALANCE") %>%
  mutate(date = mdy(date),
         month = floor_date(date, "month")) %>%
filter(month >= "2022-01-01",
       month < "2022-08-01") 

min_balances <- 
  balances %>%
  group_by(month) %>%
  filter(balance == min(balance)) %>%
  ungroup() 


f <- 
  balances %>%
  group_by(month) %>%
  summarize(foo = quantile(balance, .03)) %>%
  ungroup() %>%
  summarize(q = quantile(foo, .03)) %>%
  pull()

balances %>%
  ggplot(aes(date, balance)) +
  geom_path() +
  geom_hline(yintercept = f)

min_balances %>%
  ggplot(aes(date, balance)) +
  geom_path() +
  ggtitle("minimum balance")

```


For example, you had a $620 total return on a $2,000 investment over three years. So, your total return is 31 percent. Your annualized return is 9.42 percent. This is derived by doing the following calculation: (1+.31)^(1/3) - 1 = 9.42 percent. The standard formula for computing annualized return is AR=(1+return)1/years- 1.



```{r}


investments <-
  read_sheet("https://docs.google.com/spreadsheets/d/1SUvyFzTDKHP_AOXjkQeplC9ovJjwPBjxbTauNOSq4Ks/edit#gid=249938722",
    sheet = "Retirement - Balances"
  ) %>%
  slice_head(n = 10) %>%
  pivot_longer(-Account, names_to = "month") %>%
  mutate(
    month = my(month),
    year = year(month)
  )
  
investments %>%  
  ggplot(aes(month, value, color = Account)) +
  facet_wrap(vars(Account)) +
  geom_path() +
  theme(legend.position = "none") +
  scale_y_continuous(labels=scales::dollar_format()) 

investments %>%
  group_by(month) %>%
  summarize(total = sum(value, na.rm = TRUE)) %>%
  ggplot(aes(month, total)) + geom_path() +
  scale_y_continuous(labels=scales::dollar_format()) +
  ggtitle("Total Investments")

# get the beginning and current amounts for all accounts; calculate gains
investments %>%
  group_by(Account) %>%
  filter(month == min(month) | month == max(month)) %>%
  select(Account, month, value) %>%
  pivot_wider(names_from = month, values_from = value) %>%
  select(Account, start = `2018-06-01`, current = `2022-05-01`) %>%
  mutate(
    # fees = case_when(
    #   str_detect(Account, "Park Ave") ~ .014,
    #   Account == "Betterment (IRA)" ~ 0.0025,
    #   TRUE ~ NA_character_
    # ),
    gain = current - start,
    pct_gain = gain / start * 100,
    simple_annual_pct = pct_gain / 4
  )

```



