```{r}
library(tidyverse)
library(tidymodels)
library(lubridate)
library(vip)



fgt <- theme(
  panel.background = element_rect(color = "lightgrey", fill = "white"),
  axis.title = element_text(family = "Lato"),
  axis.text = element_text(family = "Lato"),
  legend.title = element_text(family = "Lato"),
  legend.text = element_text(family = "Lato"),
  legend.background = element_rect(fill = "white"),
  legend.key = element_rect(fill = "white"),
  plot.title = element_text(family = "Lato"),
  panel.grid.major = element_line(size = .1, color = "lightgrey"),
  panel.grid.minor = element_line(size = 0),
  # strip.background = element_rect(fill = "#8e001c"),
  strip.text = element_text(family = "Lato")
)

fg_db <- dplyr::src_mysql(
  dbname = Sys.getenv("FG_DB"),
  host = Sys.getenv("FG_HOST"),
  user = Sys.getenv("FG_USER"),
  password = Sys.getenv("FG_PW")
)

TWILIO_SID <- Sys.getenv("TWILIO_SID")
TWILIO_TOKEN <- Sys.getenv("TWILIO_TOKEN")
twilio_number <- Sys.getenv("twilio_number")

send_message <- function(msg) {
  tw_send_message(from = twilio_number, to = "5123505107", body = msg)
}
```

get, clean, mutate, and join data

```{r, message=FALSE}



year_to_predict <- 2020
data_min <- year_to_predict - 16
data_max <- year_to_predict - 1

con <-
  DBI::dbConnect(RMariaDB::MariaDB(),
    dbname = Sys.getenv("FG_DB"),
    host = Sys.getenv("FG_HOST"),
    user = Sys.getenv("FG_USER"),
    password = Sys.getenv("FG_PW"),
    port = 5001,
    ssl.ca = "~/Documents/skysql_fangraphs-db.pem"
  )

player_info_query <-
  dbSendQuery(con, "select pi.PlayerId as playerid, pi.FirstName, pi.LastName, sbmp.Season, sbmp.AVG as batting_average, sbmp.PA as plate_appearances,
  sbmp.HR as home_runs, sbmp.RBI as rbi, sbmp.OPS as ops, sbmp.SB as stolen_bases, sbmp.Fielding as defense, sbmp.G as games_played, sbmp.ValueW as WAR,
  st.TeamId, st.W / (st.W + st.L) AS team_PCT, st.League, st.G as team_games, st.AbbName as team, st.Division
  from player_info pi 
  inner join stats_batting_master_pfx sbmp on pi.PlayerId = sbmp.PlayerId
  inner join season_team st on sbmp.TeamId = st.TeamId AND sbmp.Season = st.Season
  where pi.Position != \'P\'
  and sbmp.Type = 0")

# fetch data, join with list of MVP's, clean up data, and compute ranks
player_data <-
  dbFetch(player_info_query) %>%
  as_tibble() %>%
  unite(player_name, FirstName, LastName, sep = " ") %>%
  mutate(League = factor(League)) %>%
  full_join(read_csv("mlb season awards - MVPs.csv") %>%
    mutate(
      player_name = str_replace_all(
        player_name,
        c(
          "Cal Ripken, Jr." = "Cal Ripken",
          "Ken Griffey, Jr." = "Ken Griffey Jr."
        )
      ),
      player_name = if_else(Season %in% c(1996, 1998) & League == "AL", "Juan Gonzalez",
        if_else(Season == 1999 & League == "AL", "Ivan Rodriguez",
          if_else(Season == 2017 & League == "AL", "Jose Altuve",
            player_name
          )
        )
      ),
      League = factor(League),
      is_mvp = 1
    ), by = c("Season", "player_name", "League")) %>%
  replace_na(list(is_mvp = 0))

dbClearResult(player_info_query)

dbDisconnect(con)

# compute where each team finished in its division for the year
season_team_ranks <-
  player_data %>%
  distinct(Season, League, Division, TeamId, team, team_PCT) %>%
  group_by(Season, League, Division) %>%
  mutate(team_division_rank = min_rank(-team_PCT))

master_df <-
  inner_join(player_data, season_team_ranks, by = c("Season", "TeamId", "team", "League", "Division", "team_PCT")) %>%

  # prevent small-sample rate stats from leading the league. 2.93 PA/Game is the fewest any MVP ever had -- Stargell, 1979
  filter(plate_appearances >= 2.93 * (team_games)) %>%
  group_by(Season, League) %>%

  # compute player's season-league ranking in major stats, where a rank of 1 indicates first place/league-leading.
  mutate(
    league_ops_rank = min_rank(-ops),
    league_hr_rank = min_rank(-home_runs),
    league_war_rank = min_rank(-WAR),
    league_sb_rank = min_rank(-stolen_bases),
    league_avg_rank = min_rank(-batting_average),
    league_rbi_rank = min_rank(-rbi),
    is_mvp = factor(is_mvp, levels = c("1", "0"))
  ) %>%
  ungroup() %>%
  dplyr::select(playerid, player_name, Season, League, team, contains("rank"), is_mvp)

```


```{r}

year_to_predict == year(Sys.Date())

mvp_split <-
  master_df %>%
  # train model only on players who have been considered for the HOF
  filter(Season != year_to_predict) %>%
  dplyr::select(-playerid, -player_name, -team, -League) %>%
  initial_split(strata = is_mvp, prop = 0.8)

mvp_train <- training(mvp_split)
mvp_test <- testing(mvp_split)

# adapted from https://juliasilge.com/blog/tidymodels-ml-course/


xgb_spec <-
  boost_tree(
    trees = 500,
    tree_depth = tune(), min_n = tune(),
    loss_reduction = tune(), ## first three: model complexity
    sample_size = tune(), mtry = tune(), ## randomness
    learn_rate = tune(), ## step size
  ) %>%
  set_engine("xgboost") %>%
  set_mode("classification")

xgb_grid <- grid_latin_hypercube(
  tree_depth(),
  min_n(),
  loss_reduction(),
  sample_size = sample_prop(),
  finalize(mtry(), mvp_train),
  learn_rate(),
  size = 10
)

xgb_wf <- workflow() %>%
  add_formula(is_mvp ~ .) %>%
  add_model(xgb_spec)

xgb_wf

mvp_folds <- vfold_cv(mvp_train, strata = is_mvp)

doParallel::registerDoParallel()

xgb_res <- tune_grid(
  xgb_wf,
  resamples = mvp_folds,
  grid = xgb_grid,
  control = control_grid(save_pred = TRUE)
)

xgb_res %>%
  collect_metrics() %>%
  filter(.metric == "roc_auc") %>%
  dplyr::select(mean, mtry:sample_size) %>%
  pivot_longer(mtry:sample_size,
    values_to = "value",
    names_to = "parameter"
  ) %>%
  ggplot(aes(value, mean, color = parameter)) +
  geom_point(alpha = 0.8, show.legend = FALSE) +
  facet_wrap(~parameter, scales = "free_x") +
  labs(x = NULL, y = "AUC")

best_auc <- select_best(xgb_res, "roc_auc")


final_xgb <- finalize_workflow(
  xgb_wf,
  best_auc
)

# importance plot
final_xgb %>%
  fit(data = mvp_train) %>%
  pull_workflow_fit() %>%
  vip(geom = "point")

final_res <- last_fit(final_xgb, mvp_split)

collect_metrics(final_res)

final_res %>%
  collect_predictions() %>%
  mutate(pred_mvp = if_else(.pred_class == 0, 0, 1)) %>%
  roc_curve(is_mvp, pred_mvp) %>%
  ggplot(aes(x = 1 - specificity, y = sensitivity)) +
  geom_line(size = 1.5, color = "midnightblue") +
  geom_abline(
    lty = 2, alpha = 0.5,
    color = "gray50",
    size = 1.2
  )

# fit the final model and predict this year's MVP's
mdl <-
  final_xgb %>%
  fit(data = mvp_train)

master_df %>%
  filter(Season == current_year) %>%
  bind_cols(predict(mdl, new_data = ., type = "prob")) %>%
  mutate(prob_mvp = 100 * .pred_1) %>%
  group_by(League) %>%
  slice_max(n = 10, order_by = prob_mvp) %>%
  ggplot(aes(reorder(player_name, prob_mvp), prob_mvp)) + geom_col() + coord_flip() +
  facet_wrap(vars(League), scales = "free_y")

# at this point can I just use predict() on the 2021 data??
```



```{r}


# compute total games playes in field as well as primary position. the former will be used to
# identify DH's
fielding_info <- fg_db %>%
  tbl("stats_fielding") %>%
  filter(
    Season >= data_min,
    Season <= year_to_predict,
    Position != "OF", # omit these rows; they're totals of distinct LF/CF/RF playing time
    Position != "P",
    Type == 0
  ) %>%
  dplyr::select(Season, playerid = PlayerId, Position, innings = Inn, G) %>%
  collect(n = Inf) %>%
  group_by(Season, playerid) %>%
  mutate(games_in_field = sum(G)) %>%
  arrange(desc(innings)) %>%
  filter(row_number() == 1) %>%
  dplyr::select(Season, playerid, Position, games_in_field)
```

```{r, message=FALSE, echo=FALSE}

# make testing partition
# remove informational paramters i don't want the model to look at as well as the year we're predicting
filtered_data <-
  master_df %>%
  filter(Season != year_to_predict) %>%
  dplyr::select(Season, League, player_name, team_PCT, contains("dist_from_lead"), is_mvp)

# create data partition of 25% of the dataset.
test_partition <- createDataPartition(filtered_data$is_mvp, p = 0.25)

# use 75% of the data for model training
train_df <-
  filtered_data %>%
  filter(!row_number() %in% test_partition$Resample1) %>%
  dplyr::select(-Season, -player_name) # remove Season and players' names factors. we leave them in the test DF, so I can correctly predict MVP's

# hold out 25% of the data for testing the model
test_df <-
  filtered_data %>%
  filter(row_number() %in% test_partition$Resample1)

# cross-validate model on data from previous years so we can apply it to 2018 data
control_parameters <- trainControl(
  method = "cv",
  number = 10,
  search = "grid",
  allowParallel = TRUE,
  classProbs = TRUE,
  summaryFunction = prSummary
)

parameter_grid <- expand.grid(
  nrounds = c(100, 250, 500),
  eta = c(.001, 0.1, 0.2),
  max_depth = c(5, 15),
  gamma = 10,
  colsample_bytree = c(0.9, 0.95, 1),
  min_child_weight = c(0.5, 1, 3),
  subsample = c(0.2, 0.5, 0.7)
)

mvp_predictor <- train(is_mvp ~ .,
  data = train_df,
  method = "xgbTree",
  trControl = control_parameters,
  tuneGrid = parameter_grid,
  metric = "AUC"
)

send_message("MVP predictor model is finished training!")

# evaluate model on test dataset

mvp_model_test <-
  test_df %>%
  dplyr::select(-Season, -player_name) %>% # remove variables not used in model
  predict.train(mvp_predictor, newdata = ., type = "prob") %>%
  bind_cols(test_df) %>%
  group_by(Season, League) %>%
  mutate(
    pred_mvp = if_else(Yes == max(Yes), "Yes", "No"),
    is_mvp = factor(is_mvp, levels = c("Yes", "No")),
    pred_mvp = factor(pred_mvp, levels = c("Yes", "No"))
  ) %>%

  # filter out seasons with pitcher MVP's, since my model doesn't know about them
  filter(
    Season != 2011 | League != "AL",
    Season != 2014 | League != "NL"
  ) %>%
  dplyr::select(player_name, Season, League, is_mvp, pred_mvp, No, Yes, everything())

# then do confusion matrix
confusionMatrix(mvp_model_test$is_mvp,
  mvp_model_test$pred_mvp,
  mode = "everything"
)

mvp_scores <-
  mvp_model_test %>%
  ungroup() %>%
  dplyr::select(prob_mvp = Yes, is_mvp) %>%
  mutate(is_mvp = if_else(is_mvp == "Yes", 1, 0)) %>%
  as.data.frame()

mvp_pr_curve <-
  pr.curve(
    scores.class0 = mvp_scores[mvp_scores$is_mvp == "1", ]$prob_mvp,
    scores.class1 = mvp_scores[mvp_scores$is_mvp == "0", ]$prob_mvp,
    curve = TRUE,
    rand.compute = TRUE
  )

y <- as.data.frame(mvp_pr_curve$curve)

ggplot(y, aes(y$V1, y$V2)) +
  geom_path(color = "#8e001c") +
  ylim(0, 1) +
  fgt +
  labs(x = "Recall", y = "Precision", caption = sprintf("Area Under Precision-Recall Curve: %s", round(mvp_pr_curve$auc.integral, 3))) +
  ggtitle("Precision vs. Recall for MVP Predictor Model")

# make predictions for current year
predict_df <-
  master_df %>%
  filter(Season == year_to_predict) %>%
  dplyr::select(League, team_PCT, contains("dist_from_lead"), is_mvp)

mvp_predictions <-
  predict(mvp_predictor, newdata = predict_df, type = "prob") %>%
  mutate(prob_mvp = round(100 * Yes, 2)) %>%
  as_tibble() %>%
  dplyr::select(prob_mvp) %>%
  bind_cols(predict_df) %>%
  inner_join(master_df) %>%
  dplyr::select(playerid, player_name, League, prob_mvp, everything()) %>%
  dplyr::select(-is_mvp) %>%
  arrange(desc(prob_mvp))

# plot top 10 predictions in each league
mvp_predictions %>%
  group_by(League) %>%
  filter(row_number() <= 10) %>%
  ggplot(aes(reorder(player_name, prob_mvp), prob_mvp)) +
  geom_col(fill = "#8e001c") +
  coord_flip() +
  facet_wrap(~League, scales = "free_y") +
  fgt +
  labs(x = "", y = "Probability of Season Winning the MVP (%)") +
  ggtitle(sprintf("%s Player-Seasons with the Highest MVP Probabilities", year_to_predict))

# these probabilities don't sum to 1 because they're framed as being focused on individual players. the question I'm answering here is not "who will win the MVP?" but "if a player had a season like this, what's the probability that player will win the MVP?"
```

show predictor importance plot 

```{r, message=FALSE}

# plot variable importance
bind_cols(
  row.names(varImp(mvp_predictor)$importance) %>%
    as_tibble(),
  varImp(mvp_predictor)$importance %>%
    as_tibble()
) %>%
  filter(value != "PositionP") %>% # spurious data %>%
  mutate(value = str_replace_all(
    value,
    c(
      "team_PCT" = "Team Winning Percentage",
      "rbi_rank_league" = "RBI Rank",
      "ops_rank_league" = "OPS Rank",
      "sb_rank_league" = "SB Rank",
      "avg_rank_league" = "AVG Rank",
      "hr_rank_league" = "HR Rank",
      "PositionCF" = "Is Center Fielder?",
      "PositionLF" = "Is Left Fielder?",
      "PositionRF" = "Is Right Fielder?",
      "PositionC" = "Is Catcher?",
      "Position2B" = "Is Second Baseman?",
      "PositionSS" = "Is Shortstop?",
      "PositionDH" = "Is Designated Hitter?",
      "Position3B" = "Is Third Baseman?",
      "pa_rank_league" = "PA Rank",
      "defense_rank_league" = "DEF Rank",
      "LeagueNL" = "Is National League?",
      "war_rank_league" = "WAR Rank"
    )
  )) %>%
  ggplot(aes(reorder(value, Overall), Overall)) +
  geom_col(fill = "#8e001c") +
  coord_flip() +
  fgt +
  labs(x = "", y = "Relative Importance") +
  ggtitle(sprintf("What Factors are Important in MVP Voting? (%s - %s)", data_min, data_max))

# top 10 contenders in each league
```

for informational purposes, show the kind of data the model is trained on

```{r}

master_df %>%
  filter(Season != year_to_predict) %>%
  mutate(team_PCT = round(team_PCT, 3)) %>%
  dplyr::select(
    Player = player_name, League, Season, Position, `Team Winning Percentage` = team_PCT,
    `RBI Rank` = rbi_rank_league, `OPS Rank` = ops_rank_league, `SB Rank` = sb_rank_league,
    `AVG Rank` = avg_rank_league, `HR Rank` = hr_rank_league, `WAR Rank` = war_rank_league,
    `DEF Rank` = defense_rank_league
  ) %>%
  sample_n(5) %>%
  write_csv("mvp_predictor_informational.csv")
```
