```{r}
library(tidyverse)
library(RMySQL)
library(tidytext) # for reorder_within: https://juliasilge.com/blog/reorder-within/
library(styler)
library(ggridges)
library(glue)
library(tidytext)

fgt <- theme(
  panel.background = element_rect(color = "lightgrey", fill = "white"),
  axis.title = element_text(family = "Lato"),
  axis.text = element_text(family = "Lato"),
  legend.title = element_text(family = "Lato"),
  legend.text = element_text(family = "Lato"),
  legend.background = element_rect(fill = "white"),
  legend.key = element_rect(fill = "white"),
  plot.title = element_text(family = "Lato"),
  panel.grid.major = element_line(size = .1, color = "lightgrey"),
  panel.grid.minor = element_line(size = 0),
  # strip.background = element_rect(fill = "#50ae26"),
  strip.text = element_text(family = "Lato")
)

}
```


gather data from statcast

```{r}

con <-
  DBI::dbConnect(RMariaDB::MariaDB(),
    dbname = Sys.getenv("FG_DB"),
    host = Sys.getenv("FG_HOST"),
    user = Sys.getenv("FG_USER"),
    password = Sys.getenv("FG_PW"),
    port = 5001,
    ssl.ca = "~/Documents/skysql_fangraphs-db.pem"
  )


statcast_events_q <- dbSendQuery(con, "select distinct game_year, home_team, away_team, inning, inning_top_bottom, des
                          from gd_savant_new
                          where des != ''")

events <-
  dbFetch(statcast_events_q) %>%
  as_tibble()

dbClearResult(statcast_events_q)

dbDisconnect(con)

```

```{r, fig.height = 5}
oob_season_team <-
  events %>% 
  mutate(batting_team = if_else(inning_top_bottom == "N", home_team, away_team)) %>%
  filter(str_detect(des, "out at 1st on|out at 2nd on|out at 3rd on|out at home on")) %>% 
  count(game_year, batting_team, name="oob") %>%
  mutate(oob_per_game = case_when(
    game_year %in% c(2015, 2016, 2017, 2018, 2019) ~ round(oob / 162, 3),
    game_year == 2020 ~ round(oob/60, 3),
    game_year == 2021 ~ round(oob/77, 3)
  ))

# which teams/seasons had the largest increase in OOB?
oob_changes <-
  oob_season_team %>% 
  group_by(batting_team) %>% 
  arrange(game_year, .by_group = TRUE) %>% 
  mutate(label = glue("{lag(game_year)} - {game_year}"), 
         oob_change = oob - lag(oob),
         oob_rate_change = oob_per_game - lag(oob_per_game)) 

oob_season_team %>% 
  group_by(game_year) %>%
  ggplot(aes(game_year, oob_per_game, group = game_year)) + 
  geom_boxplot() + geom_jitter()

oob_season_team %>% 
  ggplot(aes(game_year, oob_per_game)) + 
  geom_point() + geom_path() +
  facet_wrap(vars(batting_team))
  
```



