

```{r}
library(tidyverse)
library(stringr)
library(RMySQL)
library(lubridate)
library(xgboost)
library(caret)
library(e1071)
library(twilio)
library(styler)

fgt <- theme(
  panel.background = element_rect(color = "lightgrey", fill = "white"),
  axis.title = element_text(family = "Lato"),
  axis.text = element_text(family = "Lato"),
  legend.title = element_text(family = "Lato"),
  legend.text = element_text(family = "Lato"),
  legend.background = element_rect(fill = "white"),
  legend.key = element_rect(fill = "white"),
  plot.title = element_text(family = "Lato"),
  panel.grid.major = element_line(size = .1, color = "lightgrey"),
  panel.grid.minor = element_line(size = 0),
  # strip.background = element_rect(fill = "#50ae26"),
  strip.text = element_text(family = "Lato")
)

fg_db <- dplyr::src_mysql(
  dbname = Sys.getenv("FG_DB"),
  host = Sys.getenv("FG_HOST"),
  user = Sys.getenv("FG_USER"),
  password = Sys.getenv("FG_PW")
)

TWILIO_SID <- Sys.getenv("TWILIO_SID")
TWILIO_TOKEN <- Sys.getenv("TWILIO_TOKEN")
twilio_number <- Sys.getenv("twilio_number")

send_message <- function(msg) {
  tw_send_message(from = twilio_number, to = "5123505107", body = msg)
}
```


who is throwing pitches they shouldn't? or who needs to re-sequence, or adjust mechanics/spin/velo/etc. of a certain pitch?

look for pitchers to throw a high % of pitch types, in certain zones, to certain-handed batters, that get smacked for a high xWOBA

get data

```{r}

#get MLBAM ID's and FG Player ID's, so I can get FG stats and position info using the player's MLBAM ID
id_info <- fg_db %>%
  tbl("playerid_lookup") %>%
  dplyr::select(mlbamid, playerid) %>%
  collect(n=Inf)

# get player ID's of pitchers and whether they are a starter or reliever.
pitcher_type <- fg_db %>%
  tbl("player_info") %>%
  filter(BISPosition %in% c("SP", "RP")) %>%
  dplyr::select(playerid = PlayerId, position = BISPosition) %>%
  collect(n=Inf)

data <-
  fg_db %>%
  tbl("gd_savant_new") %>%

  # try hard to get only legit data. documentation: https://baseballsavant.mlb.com/csv-docs
  filter(
    pitch_type %in% c("FA", "FF", "FT", "FC", "FS", "SI", "SF", "SL", "CH", "CB", "CU", "KC", "KN", "EP"), # get legit pitch types only
    game_type %in% c("R", "F", "D", "L", "W"), # ignore spring training, etc. games
    zone != 0 # ignore invalid strikezone data
  ) %>%
  dplyr::select(pitcher, player_name, game_year, p_throws, pitch_type, balls, strikes, zone, stand, description, xwoba) %>%
  collect(n = Inf) %>%
  inner_join(id_info, by=c("pitcher" = "mlbamid")) %>%
  inner_join(pitcher_type, by="playerid")
  
```

```{r}

total_pitches_to_each_side_cutoff <- 1

# compute median xWOBA of each pitch type for both starters and relievers. we'll use this value later to determine
# whether a pitch produced a 'good' result or not
median_xwoba_2019 <-
  data %>%
  filter(
    str_detect(description, "hit_into_play"),
    game_year == 2019
  ) %>%
  group_by(position, pitch_type) %>%
  summarize(median_xwoba = median(xwoba))


data_grouped <-
  data %>%
  filter(
    game_year == 2019, # filter to 2019 to focus on advice that's immediately actionable
    description != "foul"
  ) %>% # do not count foul balls as either good or bad
  inner_join(median_xwoba_2019, by=c("position", "pitch_type")) %>%  # add median xWOBA for each position type
  mutate(
    zone_type_vertical = case_when(
      zone %in% c(11, 12, 1, 2, 3) ~ "High",
      zone %in% c(4, 5, 6) ~ "Middle",
      zone %in% c(7, 8, 9, 13, 14) ~ "Low"
    ),
    zone_type_horizontal = case_when(
      zone %in% c(2, 5, 8) ~ "Middle",
      stand == "R" & zone %in% c(11, 13) ~ "Inside",
      stand == "R" & zone %in% c(1, 4, 7) ~ "In",
      stand == "R" & zone %in% c(3, 6, 9) ~ "Away",
      stand == "R" & zone %in% c(12, 14) ~ "Outside",
      stand == "L" & zone %in% c(11, 13) ~ "Outside",
      stand == "L" & zone %in% c(1, 4, 7) ~ "Away",
      stand == "L" & zone %in% c(3, 6, 9) ~ "In",
      stand == "L" & zone %in% c(12, 14) ~ "Inside"
    ),

    # define a good pitch as one that is either a called/swinging strike or gets hit for a sub-median xWOBA
    # remember, foul balls are not counted as either good or bad
    outcome = if_else(str_detect(description, "strike") |
      (str_detect(description, "hit_into_play") & xwoba <= median_xwoba), "good", "bad")
  ) %>%
  unite(zone_desc, zone_type_vertical, zone_type_horizontal, sep = " and ") %>%
  unite(count, balls, strikes, sep = "-") %>%
  group_by(player_name, game_year, p_throws, stand) %>%
  mutate(total_pitches_to_batters_of_this_hand = n()) %>%
  filter(total_pitches_to_batters_of_this_hand >= total_pitches_to_each_side_cutoff) %>% # try to get only full time pitchers
  group_by(player_name, game_year, p_throws, position, count, zone_desc, stand, pitch_type, outcome) %>%
  summarize(
    num_pitches = n()
  ) %>%
  mutate(percentage = round(num_pitches / sum(num_pitches) * 100, 1))
#  mutate(pitch_percentage = round(num_pitches / total_pitches_to_batters_of_this_hand * 100, 1))
```



```{r}
# compute good-pitch rate per pitcher for 2019
by_pitcher <-
  data_grouped %>%
  group_by(player_name) %>%
  mutate(total_pitches = sum(num_pitches)) %>%
  # filter(total_pitches < 500) %>% # get starters
  filter(outcome == "good") %>%
  group_by(player_name, position, total_pitches) %>%
  summarize(num_good_pitches = sum(num_pitches)) %>%
  mutate(good_pitch_percentage = round(num_good_pitches / total_pitches, 3)) %>%
  arrange(desc(good_pitch_percentage))

# when estimating good-pitch rates, take into account the total number of pitches thrown
# good pitchers will get more chances
fit <- gamlss(cbind(num_good_pitches, total_pitches - num_good_pitches) ~ log(total_pitches) + position,
  data = by_pitcher,
  family = BB(mu.link = "identity")
)

td <- tidy(fit)

mu <- fitted(fit, parameter = "mu")
sigma <- fitted(fit, parameter = "sigma")

# compute shape parameters of posterior beta curves, given data
good_pitches_est <-
  by_pitcher %>%
  ungroup() %>%
  mutate(
    mu = mu,
    alpha0 = mu / sigma,
    beta0 = (1 - mu) / sigma,
    alpha1 = alpha0 + num_good_pitches,
    beta1 = beta0 + total_pitches - num_good_pitches,
    est_good_pitch_rate = alpha1 / (alpha1 + beta1),
    low_credible = qbeta(.025, alpha1, beta1),
    high_credible = qbeta(.975, alpha1, beta1)
  ) %>%
  group_by(position) %>%
  arrange(desc(est_good_pitch_rate))

# ggplot(by_pitcher, aes(good_pitch_percentage)) + geom_histogram(binwidth = .01, aes(y = ..density..)) +
#   stat_function(
#     fun = dbeta,
#     args = list(shape1 = alpha0, shape2 = beta0),
#     lwd = 2,
#     aes(color = "All Pitchers")
#   ) +
#   labs(x = "Good Pitches per Pitch Thrown") +
#   labs(color = "Distributions") +
#   ggtitle("Probability Distribution for Good Pitch %")

# estimate good-pitch-rate by applying priors to all pitchers. also compute credible intervals

# plot prior distributions for different numbers of pitches thrown
# mu_0 <- td$estimate[1]
# mu_pitches <- td$estimate[2]
# sigma <- exp(td$estimate[3])
# 
# # compute prior distributions for several values of total pitch count
# good_pitch_rate_priors <- crossing(x = seq(0.1, .6, .01), total_pitches = c(50, 500, 1000, 1500)) %>%
#   mutate(density = dbeta(
#     x, (mu_0 + mu_pitches * log(total_pitches)) / sigma,
#     (1 - (mu_0 + mu_pitches * log(total_pitches))) / sigma
#   )) %>%
#   mutate(total_pitches = factor(total_pitches))
# 
# # plot prior distributions
# ggplot(good_pitch_rate_priors, aes(x, density, color = total_pitches, group = total_pitches)) +
#   geom_line(group = 1) + labs(x = "Estimated Good-Pitch Rate", y = "Prior Density") +
#   ggtitle("More Pitches Thrown = Increased Probability of Higher Good-Pitch Rate") +
#   xlim(0.3, 0.55)

# plot the 10 best relievers and the 10 best starters
good_pitches_est %>%
  group_by(position) %>%
  arrange(desc(est_good_pitch_rate)) %>%
  filter(row_number() <= 10) %>%
  ggplot(aes(reorder(player_name, est_good_pitch_rate), est_good_pitch_rate)) + coord_flip() +
  geom_point() + geom_errorbar(aes(ymin = low_credible, ymax = high_credible)) + facet_grid(vars(position), scales = "free_y") +
  labs(x = "", y = "Estimated Good-Pitch Rate with 95% Credible Interval") +
  ggtitle("Highest Good-Pitch Rates, 2019")

# worst pitchers
good_pitches_est %>%
  group_by(position) %>%
  arrange(est_good_pitch_rate) %>%
  filter(row_number() <= 10) %>%
  ggplot(aes(reorder(player_name, est_good_pitch_rate), est_good_pitch_rate)) + coord_flip() +
  geom_point() + geom_errorbar(aes(ymin = low_credible, ymax = high_credible)) + facet_grid(vars(position), scales = "free_y") +
  labs(x = "", y = "Estimated Good-Pitch Rate with 95% Credible Interval") +
  ggtitle("Lowest Good-Pitch Rates, 2019")
```


```{r, fig.height=5}
pitch_cutoff <- 2 # get only zones/batters who've seen at least this many pitches, from the pitcher in this count

# how to incorporate the count in it? that matters

data_grouped %>%
  filter(
    outcome == "good",
    num_pitches >= pitch_cutoff
  ) %>%
  unite(label, player_name, pitch_type, count, zone_desc, stand, sep = " - ") %>%
  arrange(desc(percentage)) %>%
  head(25) %>%
  ggplot(aes(reorder(label, percentage), percentage)) + geom_col() + coord_flip() +
  ggtitle("Mean xWOBA by Pitch Type, Location, and Batter Handedness",
    subtitle = glue("For pitches thrown at least {percentage_cutoff}% of the time in that location to batters of that hand
                          For pitchers with at least {total_pitches_to_each_side_cutoff * 2} pitches in 2019")
  ) +
  labs(
    x = "", y = "Percentage of Pitches that are Good",
    caption = "Good pitch: swinging strike, called strike, or batted ball with xWOBA less than the league median xWOBA"
  )

data_grouped %>%
  filter(
    outcome == "good",
    num_pitches >= pitch_cutoff
  ) %>%
  unite(label, player_name, pitch_type, count, zone_desc, stand, sep = " - ") %>%
  arrange(desc(percentage)) %>%
  tail(25) %>%
  ggplot(aes(reorder(label, -percentage), percentage)) + geom_col() + coord_flip() +
  ggtitle(" by Pitch Type, Location, and Batter Handedness",
    subtitle = glue("For pitches thrown at least {percentage_cutoff}% of the time in that location to batters of that hand
                          For pitchers with at least {total_pitches_to_each_side_cutoff * 2} pitches in 2019")
  ) +
  facet_grid(vars(count)) +
  labs(x = "", y = "Percentage of Pitches that are Good")
```


