```{r setup, include=FALSE, echo=FALSE}


library(tidyverse)
library(stringr)
library(plotly)
library(RMySQL)

fgt = theme(
  panel.background = element_rect(color = "lightgrey", fill = "white"),
  axis.title = element_text(family = "Lato"),
  axis.text = element_text(family = "Lato"),
  legend.title = element_text(family = "Lato"),
  legend.text = element_text(family = "Lato"),
  legend.background = element_rect(fill = "white"),
  legend.key = element_rect(fill = "white"),
  plot.title = element_text(family = "Lato"),
  panel.grid.major = element_line(size = .1, color = "lightgrey"),
  panel.grid.minor = element_line(size = 0),
  strip.background = element_rect(fill = "#50ae26"),
  strip.text = element_text(color="white", family="Lato")
  )

fg_db <- dplyr::src_mysql(dbname = Sys.getenv("FG_DB"), 
                            host = Sys.getenv("FG_HOST"), 
                            user = Sys.getenv("FG_USER"),
                            password = Sys.getenv("FG_PW"))
```

### Get data

```{r}

gd_info <- fg_db %>%
  tbl("gd_roster") %>%
  select(mlbamid, playerid)

fg_info <- fg_db %>%
  tbl("player_info") %>%
  select(PlayerId, FirstName, LastName, BISPosition) %>%
  collect(n=Inf)

savant_data_plate_coverage <- fg_db %>%
  tbl("gd_savant") %>%
  filter(game_year >= 2016) %>%
  select(batter, player_name, game_year, description, px, pz) %>%
  inner_join(gd_info, by=c("batter" = "mlbamid")) %>%
  collect(n=Inf) %>%
  filter(str_detect(description, "In play")) %>%
  mutate(px = as.numeric(px),
         pz = as.numeric(pz)) %>%
  inner_join(fg_info, by=c("playerid" = "PlayerId")) %>%
  filter(!BISPosition %in% c("", "SP", "RP")) %>%
  mutate(Name = sprintf("%s %s", FirstName, LastName))

```

### Compute plate coverage info

```{r}
plate_coverage_raw <- savant_data_plate_coverage %>%
  group_by(Name, game_year) %>%
  summarize(num_balls_contacted = n(),
            horiz_coverage = round(mad(px), 3),
            vertical_coverage = round(mad(pz), 3)) %>%
  mutate(total_coverage = horiz_coverage * vertical_coverage) %>%
  filter(num_balls_contacted >= 50)

plate_coverage_change <- plate_coverage_raw %>%
  group_by(Name) %>%
  arrange(game_year) %>%
  mutate(horiz_diff = horiz_coverage - lag(horiz_coverage),
         vertical_diff = vertical_coverage - lag(vertical_coverage),
         total_diff = round(horiz_diff + vertical_diff, 3)) %>%
  filter(game_year == 2017)

coverage_change_plot <- ggplot(plate_coverage_change, aes(horiz_diff, vertical_diff, label=Name)) + geom_point() + fgt
ggplotly(coverage_change_plot)
```

### Boxplots for worst/best players in 2016

```{r}
example_horiz_coverage <- savant_data %>%
  filter(game_year == 2016,
         str_detect(description, "In play"),
         Name %in% c("Caleb Joseph", "Delino DeShields")) %>%
  select(Name, px)

ggplot(example_horiz_coverage, aes(y=px, x=Name)) + geom_boxplot() + geom_jitter() + coord_flip() + fgt +
  ggtitle("Worst and Best Horizontal Plate Coverage, 2016") + labs(x="", y="Horizontal Location of Contact (feet)")

example_vertical_coverage <- savant_data %>%
  filter(game_year == 2016,
         str_detect(description, "In play"),
         Name %in% c("Taylor Motter", "Corey Dickerson")) %>%
  select(Name, pz)

ggplot(example_vertical_coverage, aes(y=pz, x=Name)) + geom_boxplot() + geom_jitter() + coord_flip() + fgt +
  ggtitle("Worst and Best Vertical Plate Coverage, 2016") + labs(x="", y="Vertical Location of Contact (feet)")
           
```


### Boxplots for 2016 - 2017 changers

biggest increase in horizontal coverage: ender inciarte
biggest decrease in horizontal coverage: maikel franco

biggest increase in vertical coverage: jose peraza 
biggest decrease in vertical coverage: travis shaw

Figure out how to order these graphs by year.

```{r}

inciarte_plate_coverage <- savant_data %>%
  filter(game_year >= 2016,
         str_detect(description, "In play"),
         Name == "Ender Inciarte",
         pz > 0) %>%
  select(game_year, px, pz)

franco_plate_coverage <- savant_data %>%
  filter(game_year >= 2016,
         str_detect(description, "In play"),
         Name == "Maikel Franco",
         pz > 0) %>%
  select(game_year, px, pz)


peraza_plate_coverage <- savant_data %>%
  filter(game_year >= 2016,
         str_detect(description, "In play"),
         Name == "Jose Peraza",
         pz > 0) %>%
  select(game_year, px, pz)

shaw_plate_coverage <- savant_data %>%
  filter(game_year >= 2016,
         str_detect(description, "In play"),
         Name == "Travis Shaw",
         pz > 0) %>%
  select(game_year, px, pz)

ggplot(inciarte_plate_coverage, aes(y=px, x=as.character(game_year)))+ 
  geom_boxplot() + geom_jitter() + coord_flip() + fgt + ggtitle("Ender Inciarte Horizontal Plate Coverage, 2016 - 2017") +
  labs(x="", y="Horizontal Location of Contact (feet)")

ggplot(franco_plate_coverage, aes(y=px, x=as.character(game_year))) + geom_boxplot() + geom_jitter() + coord_flip() + fgt +
  ggtitle("Maikel Franco Horizontal Plate Coverage, 2016 - 2017") + labs(x="", y="Horizontal Location of Contact (feet)")

ggplot(peraza_plate_coverage, aes(y=pz, x=as.character(game_year))) + geom_boxplot() + geom_jitter() + fgt +
  ggtitle("Jose Peraza Vertical Plate Coverage, 2016 - 2017") + labs(x="", y="Vertical Location of Contact (feet)")

ggplot(shaw_plate_coverage, aes(y=pz, x=as.character(game_year))) + geom_boxplot() + geom_jitter() + fgt +
  ggtitle("Travis Shaw Vertical Plate Coverage, 2016 - 2017") + labs(x="", y="Vertical Location of Contact (feet)")


```