```{r setup, include=FALSE, echo=FALSE}


library(tidyverse)
library(stringr)
library(plotly)
library(RMySQL)
library(broom)

fgt = theme(
  panel.background = element_rect(color = "lightgrey", fill = "white"),
  axis.title = element_text(family = "Lato"),
  axis.text = element_text(family = "Lato"),
  legend.title = element_text(family = "Lato"),
  legend.text = element_text(family = "Lato"),
  legend.background = element_rect(fill = "white"),
  legend.key = element_rect(fill = "white"),
  plot.title = element_text(family = "Lato"),
  panel.grid.major = element_line(size = .1, color = "lightgrey"),
  panel.grid.minor = element_line(size = 0),
  #strip.background = element_rect(fill = "#50ae26"),
  strip.text = element_text(family="Lato")
  )

fg_db <- dplyr::src_mysql(dbname = Sys.getenv("FG_DB"), 
                            host = Sys.getenv("FG_HOST"), 
                            user = Sys.getenv("FG_USER"),
                            password = Sys.getenv("FG_PW"))
```

### Get data

```{r}

# gd_info <- fg_db %>%
#   tbl("gd_roster") %>%
#   dplyr::select(mlbamid, playerid)

id_info <- fg_db %>%
  tbl("playerid_lookup") %>%
  dplyr::select(mlbamid, playerid) %>%
  collect(n=Inf)

fg_info <- fg_db %>%
  tbl("player_info") %>%
  filter(!BISPosition %in% c("SP", "RP")) %>%
  dplyr::select(PlayerId, FirstName, LastName, LastGame) %>%
  collect(n=Inf) %>%
  mutate(LastGame = ymd(LastGame),
         lastYear = year(LastGame)) %>%
  unite(batter_name, FirstName, LastName, sep = " ")

batting_war <- fg_db %>%
  tbl("stats_batting") %>%
  filter(Type == 0, 
         Season >= 2015) %>%
  dplyr::select(playerid, Season, wrc_plus = `wRC+`, RBI) %>%
  collect(n=Inf) %>%
  inner_join(fg_info, by=c("playerid" = "PlayerId")) %>%
  inner_join(id_info, by="playerid")


# for each spot in zone ... ratio of swings to takes? can divide px and pz into deciles to compute zones ... 

#get all pitches, then classify as swing/non-swing, then take ratio, then split by baserunner situation

#get all swings
savant_data <- fg_db %>%
  tbl("gd_savant_new") %>%
  filter(description %in% c("foul", "hit_into_play", "hit_into_play_no_out",
                            "hit_into_play_score", "swinging_pitchout", "swinging_strike",
                            "swinging_strike_blocked")) %>%
  dplyr::select(batter, pitcher = player_name, pitcher_mlbam_id = pitcher, game_date, 
                game_year, description, plate_x, plate_z,
                on_1b, on_2b, on_3b, balls, strikes, outs_when_up) %>%
  collect(n=Inf) %>%
  inner_join(batting_war, by=c("batter" = "mlbamid", "game_year" = "Season")) %>%
  mutate(plate_x = as.numeric(plate_x),
         plate_z = as.numeric(plate_z)) %>%
  #compute inches instead of feet
  mutate(px_in = plate_x * 12,
         pz_in = plate_z * 12,
         
         #don't care WHO the runners are, just where they are
         on_1b = ifelse(on_1b > 0, "Y", "N"),
         on_2b = ifelse(on_2b > 0, "Y", "N"),
         on_3b = ifelse(on_3b > 0, "Y", "N"),
         runners_on_base = paste0(on_1b, on_2b, on_3b)) %>%
  filter(balls <= 3,            #get rid of some weird data
         strikes <= 2) %>%
  unite(count, balls, strikes, sep = "-")
```

### Compute batter aggeression

```{r}

plate_discipline_overall <- savant_data %>%
  group_by(playerid, batter_name, game_year, lastYear, wrc_plus) %>%
  summarize(num_swings = n(),
            horiz_disc = round(mad(px_in), 3),
            vertical_disc = round(mad(pz_in), 3)) %>%
  mutate(discipline_sq_in = horiz_disc * vertical_disc,
         aggression_per_100_swings = discipline_sq_in / num_swings * 100) %>%
  filter(num_swings >= 200) %>%    #this is about 1/6 of a full season, to reduce survivor bias
  arrange(discipline_sq_in)

year_to_year_changes_2017 <- plate_discipline_overall %>%
  group_by(playerid) %>%
  arrange(game_year) %>%
  mutate(disc_diff = aggression_per_100_swings - lag(aggression_per_100_swings),
         wrc_diff = wrc_plus - lag(wrc_plus)) %>%
  filter(!is.na(disc_diff)) %>%
  arrange(disc_diff)



#by batter by baserunner state. who is more aggressive when there are runners on base?
plate_discipline_by_base_state <- savant_data %>%
  group_by(playerid, batter_name, game_year, last_year, runners_on_base) %>%
  summarize(num_swings = n(),
            horiz_disc = round(mad(px_in), 3),
            vertical_disc = round(mad(pz_in), 3)) %>%
  mutate(discipline_sq_in = horiz_disc * vertical_disc,
         aggression_per_100_swings = discipline_sq_in / num_swings * 100) %>%
 # filter(num_swings >= 200) %>%    #this is about 1/6 of a full season, to reduce survivor bias
  arrange(aggression_per_100_swings)


```




### plots

```{r}
ggplot(plate_discipline_overall, aes(aggression_per_100_swings, wrc_plus)) + geom_point() + 
  geom_smooth(method = "lm", formula = y ~ poly(x, 2)) +
  labs(x="Aggression (sq. inches / 100 swings)", y="wRC+") + 
  ggtitle("It Pays to be Patient at the Plate") + fgt
#per_pitch makes no mathematical sense but it equalizes folks and the top of the list 'looks' right in that
#it has really good hitters in it.

ggplot(year_to_year_changes_2017, aes(disc_diff, wrc_diff)) + geom_point() +
  geom_smooth(method="lm") + labs(x="YoY Change in Aggression (sq. in / 100 swings)", y="YoY Change in wRC+") +
  ggtitle("Year-over-Year, Expanding the Zone is Associated with a Decrease in Offense") + fgt

ggplot(plate_discipline_overall, aes(as.character(game_year),
                                     aggression_per_100_swings)) + geom_boxplot() + coord_flip() + 
  labs(x="", y="Aggression (sq. in / 100 swings)") + 
  ggtitle("Hitters Are Becoming Not Only More Similar, But Also More Aggressive") + fgt

```

### compute & plot deciles

```{r}

plate_discipline_deciles <- plate_discipline_overall %>%
  ungroup() %>%
  mutate(decile = ntile(aggression_per_100_swings, 10)) %>%
  group_by(decile) %>%
  summarize(from_disc = min(aggression_per_100_swings),
            to_disc = max(aggression_per_100_swings),
            mean_wrc_plus = mean(wrc_plus))


ggplot(plate_discipline_deciles, aes(reorder(as.character(decile), decile), mean_wrc_plus)) +
  geom_bar(stat="identity") + labs(x="Decile (1 = Low Aggression, 10 = High Aggression)", y="Mean wRC+") + fgt
```

### Models for Graphs Above

```{r}
aggression_per_100_swings_model <- lm(plate_discipline_overall$wrc_plus ~ 
                                   poly(plate_discipline_overall$aggression_per_100_swings, 2))
summary(aggression_per_100_swings_model)

#r^2 = .21!!!

discipline_augmented <- augment(aggression_per_100_swings_model)

yoy_discipline_model <- lm (year_to_year_changes_2017$wrc_diff ~ year_to_year_changes_2017$disc_diff)
summary(yoy_discipline_model)

```

### show votto & bour's aggression to demonstrate the methodology

```{r}

#votto & bour are two great examples; they're both lefties and their plots contrast well.
ggplot(savant_data %>% filter(game_year == 2017,
                              batter_name %in% c("Joey Votto", "Justin Bour")),
       aes(px_in, pz_in)) + geom_point() + facet_grid(~batter_name) + 
  ggtitle("Swings from Select Hitters, 2017") + xlim(-20, 20) +ylim(0, 60)

```


### compute pitcher aggression (that they induce in batters)

```{r}
pitcher_plate_discipline_overall <- savant_data %>%
  group_by(pitcher, game_year) %>%
  summarize(num_swings = n(),
            horiz_disc = round(mad(px_in), 3),
            vertical_disc = round(mad(pz_in), 3)) %>%
  mutate(discipline_sq_in = horiz_disc * vertical_disc,
         aggression_per_100_swings = discipline_sq_in / num_swings * 100) %>%
  filter(num_swings >= 200) %>%    #this is about 1/6 of a full season, to reduce survivor bias
  arrange(aggression_per_100_swings)

# it seems the best pitchers induce lots of swings IN the zone ... but somehow remain untouched.

#correlate discipline_per_100 to xFIP-

ggplot(savant_data %>% filter(game_year == 2017,
                              pitcher %in% c("Max Scherzer", "Hisashi Iwakuma")),
       aes(px_in, pz_in)) + geom_point() + facet_wrap(~pitcher) + 
  ggtitle("Swings Induced by Select Pitchers, 2017") + xlim(-20, 20) +ylim(0, 60)
```

### in which base-out states are hitters the most aggressive?

```{r}

#by baserunner state, count, and outs generally.
plate_discipline_by_base_out_states <- savant_data %>%
  group_by(runners_on_base, outs_when_up) %>%
  summarize(num_swings = n(),
            horiz_disc = round(mad(px_in), 3),
            vertical_disc = round(mad(pz_in), 3),
            discipline_sq_in = horiz_disc * vertical_disc,
            aggression_per_100_swings = discipline_sq_in / num_swings * 100) %>%
  filter(num_swings >= 10) %>%    
  arrange(aggression_per_100_swings)

ggplot(plate_discipline_by_base_out_states, aes(x=runners_on_base, y=as.character(outs_when_up))) +
         geom_point(aes(color=aggression_per_100_swings, size=aggression_per_100_swings)) +
  ggtitle("Hitters are Most Aggressive when a Runner's on Third Base") +
  labs(x="Runners On Base (Y = Runner, N = No Runner)", y="Outs") +
  guides(color=guide_legend(), size = guide_legend()) +
  scale_color_gradient(low="green", high = "red") + fgt

```

```{r}
# which players change their approach the most from runner-not-on-third to runner-on-third (when there are 0 outs)

player_aggression_relative <- savant_data %>%
  mutate(runner_on_third = ifelse(runners_on_base %in% c("NNY", "NYY", "YNY", "YYY"), "Y", "N")) %>%
  group_by(playerid, batter_name, lastYear, runner_on_third) %>%
  summarize(num_swings = n(),
            horiz_disc = round(mad(px_in), 3),
            vertical_disc = round(mad(pz_in), 3),
            discipline_sq_in = horiz_disc * vertical_disc,
            aggression_per_100_swings = discipline_sq_in / num_swings * 100) %>%
  filter(num_swings >= 50) %>%   #want players who've swung at least 50 times in both situations
  group_by(playerid, batter_name, lastYear) %>%
  arrange(runner_on_third) %>%
  mutate(aggression_multiplier_when_runner_on_third = aggression_per_100_swings / lag(aggression_per_100_swings)) %>%
  filter(lastYear == 2017,
         !is.na(aggression_multiplier_when_runner_on_third)) %>%
  arrange(desc(aggression_multiplier_when_runner_on_third)) %>%
  ungroup()
  
#players who change their approach the most with runners on 3rd
player_aggression_relative %>%
  dplyr::select(batter_name, aggression_multiplier_when_runner_on_third) %>%
  head(25)

#the least
player_aggression_relative %>%
  dplyr::select(batter_name, aggression_multiplier_when_runner_on_third) %>%
  tail(25)

mean(player_aggression_relative$aggression_multiplier_when_runner_on_third)

```

