---
title: "playoff-interesst"
output: html_document
date: '`r Sys.Date()`'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(baseballr)
library(httr)
library(tidyjson)
library(jsonlite)
library(styler)
library(ggrepel)
library(glue)
library(kableExtra)
```


```{r echo=FALSE, fig.width=9, message=FALSE, warning=FALSE}
# get playoff chances from ESPN
# espn <- read_html("https://www.espn.com/mlb/standings")
#
# al <- espn %>%
#   html_elements("table") %>%
#   pluck(1) %>%
#   html_table() %>%
#   bind_cols(espn %>%
#     html_elements("table") %>%
#     pluck(2) %>%
#     html_table())
#
# nl <-
#   espn %>%
#   html_elements("table") %>%
#   pluck(3) %>%
#   html_table() %>%
#   bind_cols(espn %>%
#     html_elements("table") %>%
#     pluck(4) %>%
#     html_table())
#
# playoff_chances_espn <-
#   bind_rows(al, nl) %>%
#   select(team_name = 1, poff = X12) %>%
#   filter(poff != "POFF") %>%
#   mutate(
#     team_name = case_when(
#       str_detect(team_name, "LAD") ~ "Los Angeles Dodgers",
#       str_detect(team_name, "NYY") ~ "New York Yankees",
#       str_detect(team_name, "Baltimore") ~ "Baltimore Orioles",
#       str_detect(team_name, "BOS") ~ "Boston Red Sox",
#       str_detect(team_name, "TOR") ~ "Toronto Blue Jays",
#       str_detect(team_name, "Tampa Bay") ~ "Tampa Bay Rays",
#       str_detect(team_name, "CLE") ~ "Cleveland Guardians",
#       str_detect(team_name, "Minnesota") ~ "Minnesota Twins",
#       str_detect(team_name, "White Sox") ~ "Chicago White Sox",
#       str_detect(team_name, "Detroit") ~ "Detroit Tigers",
#       str_detect(team_name, "Kansas") ~ "Kansas City Royals",
#       str_detect(team_name, "Houston") ~ "Houston Astros",
#       str_detect(team_name, "LAA") ~ "Los Angeles Angels",
#       str_detect(team_name, "Oakland") ~ "Oakland Athletics",
#       str_detect(team_name, "Seattle") ~ "Seattle Mariners",
#       str_detect(team_name, "Washington") ~ "Washington Nationals",
#       str_detect(team_name, "Miami") ~ "Miami Marlins",
#       str_detect(team_name, "NYM") ~ "New York Mets",
#       str_detect(team_name, "Philadelphia") ~ "Philadelphia Phillies",
#       str_detect(team_name, "CHC") ~ "Chicago Cubs",
#       str_detect(team_name, "Pittsburgh") ~ "Pittsburgh Pirates",
#       str_detect(team_name, "Milwaukee") ~ "Milwaukee Brewers",
#       str_detect(team_name, "Cincinnati") ~ "Cincinnati Reds",
#       str_detect(team_name, "Texas") ~ "Texas Rangers",
#       str_detect(team_name, "San Diego") ~ "San Diego Padres",
#       str_detect(team_name, "San Francisco") ~ "San Francisco Giants",
#       str_detect(team_name, "St. Louis") ~ "St. Louis Cardinals",
#       str_detect(team_name, "Colorado") ~ "Colorado Rockies",
#       str_detect(team_name, "Atlanta") ~ "Atlanta Braves",
#       str_detect(team_name, "Arizona") ~ "Arizona Diamondbacks",
#       TRUE ~ NA_character_
#     ),
#     poff_chance = as.numeric(str_extract(poff, "[:digit:]{1,3}\\.[:digit:]{1}"))
#   ) %>%
#   select(team_name, poff_chance)


# get playoff chances from baseball prospectus/PECOTA
pecota_poff <-
  read_html("https://www.baseballprospectus.com/standings/") %>%
  html_elements("table")

poff_chance_pecota <-
  pecota_poff %>%
  pluck(1) %>%
  html_table() %>%
  filter(!str_detect(`AL East`, "AL ")) %>%
  select(team_name = `AL East`, poff_chance = `Playoff%`) %>%
  bind_rows(pecota_poff %>% pluck(2) %>% html_table() %>% filter(!str_detect(`NL East`, "NL ")) %>% select(team_name = `NL East`, poff_chance = `Playoff%`)) %>%
  mutate(
    team_name = case_when(
      str_detect(team_name, "LAD") ~ "Los Angeles Dodgers",
      str_detect(team_name, "NYY") ~ "New York Yankees",
      str_detect(team_name, "Baltimore") ~ "Baltimore Orioles",
      str_detect(team_name, "BOS") ~ "Boston Red Sox",
      str_detect(team_name, "TOR") ~ "Toronto Blue Jays",
      str_detect(team_name, "Tampa Bay") ~ "Tampa Bay Rays",
      str_detect(team_name, "CLE") ~ "Cleveland Guardians",
      str_detect(team_name, "Minnesota") ~ "Minnesota Twins",
      str_detect(team_name, "CWS") ~ "Chicago White Sox",
      str_detect(team_name, "Detroit") ~ "Detroit Tigers",
      str_detect(team_name, "Kansas") ~ "Kansas City Royals",
      str_detect(team_name, "Houston") ~ "Houston Astros",
      str_detect(team_name, "LAA") ~ "Los Angeles Angels",
      str_detect(team_name, "Oakland") ~ "Oakland Athletics",
      str_detect(team_name, "Seattle") ~ "Seattle Mariners",
      str_detect(team_name, "Washington") ~ "Washington Nationals",
      str_detect(team_name, "Miami") ~ "Miami Marlins",
      str_detect(team_name, "NYM") ~ "New York Mets",
      str_detect(team_name, "Philadelphia") ~ "Philadelphia Phillies",
      str_detect(team_name, "CHC") ~ "Chicago Cubs",
      str_detect(team_name, "Pittsburgh") ~ "Pittsburgh Pirates",
      str_detect(team_name, "Milwaukee") ~ "Milwaukee Brewers",
      str_detect(team_name, "Cincinnati") ~ "Cincinnati Reds",
      str_detect(team_name, "Texas") ~ "Texas Rangers",
      str_detect(team_name, "San Diego") ~ "San Diego Padres",
      str_detect(team_name, "San Francisco") ~ "San Francisco Giants",
      str_detect(team_name, "St. Louis") ~ "St. Louis Cardinals",
      str_detect(team_name, "Colorado") ~ "Colorado Rockies",
      str_detect(team_name, "Atlanta") ~ "Atlanta Braves",
      str_detect(team_name, "Arizona") ~ "Arizona Diamondbacks",
      TRUE ~ NA_character_
    ),
    poff_chance = as.numeric(str_extract(poff_chance, "[:digit:]{1,3}\\.[:digit:]{1}"))
  )

# get odds from teamrankings.com

poff_chance_teamrankings <-
  read_html("https://www.teamrankings.com/mlb/") %>%
  html_elements("table") %>%
  pluck(1) %>%
  html_table() %>%
  mutate(
    team_name = str_replace_all(Team, c(
      "LA Dodgers" = "Los Angeles Dodgers",
      "NY Yankees" = "New York Yankees",
      "Houston" = "Houston Astros",
      "Toronto" = "Toronto Blue Jays",
      "NY Mets" = "New York Mets",
      "Atlanta" = "Atlanta Braves",
      "Philadelphia" = "Philadelphia Phillies",
      "Tampa Bay" = "Tampa Bay Rays",
      "San Diego" = "San Diego Padres",
      "Chi Sox" = "Chicago White Sox",
      "Milwaukee" = "Milwaukee Brewers",
      "Seattle" = "Seattle Mariners",
      "St. Louis" = "St. Louis Cardinals",
      "Boston" = "Boston Red Sox",
      "Minnesota" = "Minnesota Twins",
      "LA Angels" = "Los Angeles Angels",
      "SF Giants" = "San Francisco Giants",
      "Cleveland" = "Cleveland Guardians",
      "Texas" = "Texas Rangers",
      "Miami" = "Miami Marlins",
      "Baltimore" = "Baltimore Orioles",
      "Chi Cubs" = "Chicago Cubs",
      "Arizona" = "Arizona Diamondbacks",
      "Cincinnati" = "Cincinnati Reds",
      "Detroit" = "Detroit Tigers",
      "Kansas City" = "Kansas City Royals",
      "Oakland" = "Oakland Athletics",
      "Colorado" = "Colorado Rockies",
      "Washington" = "Washington Nationals",
      "Pittsburgh" = "Pittsburgh Pirates"
    )),
    team_name = str_extract(team_name, ".*[a-z]"),
    poff_chance = as.numeric(str_extract(Playoffs, "[:digit:]{1,3}\\.[:digit:]{1}"))
  ) %>%
  select(team_name, poff_chance)

# get odds from numberFire
numberfire <-
  read_html("https://www.numberfire.com/mlb/teams/power-rankings") %>%
  html_elements("table") %>%
  html_table()

poff_chance_numberfire <-
  numberfire %>%
  pluck(1) %>%
  bind_cols(
    numberfire %>%
      pluck(2)
  ) %>%
  mutate(
    team_name = str_extract(Team, ".*[a-z]"),
    poff_chance = as.numeric(str_extract(Playoffs, "[:digit:]{1,3}\\.[:digit:]{1}"))
  ) %>%
  select(team_name, poff_chance)

# get FG playoff odds
headers <- c(
  "user-agent" = "Mozilla/5.0",
  "content-type" = "application/json;charset=UTF-8"
)

url <- glue("https://www.fangraphs.com/api/playoff-odds/odds?dateEnd={Sys.Date()}&dateDelta=&projectionMode=2&standingsType=div")

poff_chances_fg <-
  GET(url, add_headers(headers)) %>%
  content() %>%
  as_tbl_json() %>%
  # gather_array() %>%
  spread_all() %>%
  select(abbName, poff_chance = endData.poffTitle) %>%
  mutate(poff_chance = round(poff_chance, 3) * 100) %>%
  as_tibble() %>%
  mutate(team_name = case_when(
    abbName == "LAA" ~ "Los Angeles Angels",
    abbName == "BAL" ~ "Baltimore Orioles",
    abbName == "BOS" ~ "Boston Red Sox",
    abbName == "CHW" ~ "Chicago White Sox",
    abbName == "CLE" ~ "Cleveland Guardians",
    abbName == "DET" ~ "Detroit Tigers",
    abbName == "KCR" ~ "Kansas City Royals",
    abbName == "MIN" ~ "Minnesota Twins",
    abbName == "NYY" ~ "New York Yankees",
    abbName == "OAK" ~ "Oakland Athletics",
    abbName == "SEA" ~ "Seattle Mariners",
    abbName == "TBR" ~ "Tampa Bay Rays",
    abbName == "TEX" ~ "Texas Rangers",
    abbName == "TOR" ~ "Toronto Blue Jays",
    abbName == "ARI" ~ "Arizona Diamondbacks",
    abbName == "ATL" ~ "Atlanta Braves",
    abbName == "CHC" ~ "Chicago Cubs",
    abbName == "CIN" ~ "Cincinnati Reds",
    abbName == "COL" ~ "Colorado Rockies",
    abbName == "MIA" ~ "Miami Marlins",
    abbName == "HOU" ~ "Houston Astros",
    abbName == "LAD" ~ "Los Angeles Dodgers",
    abbName == "MIL" ~ "Milwaukee Brewers",
    abbName == "WSN" ~ "Washington Nationals",
    abbName == "NYM" ~ "New York Mets",
    abbName == "PHI" ~ "Philadelphia Phillies",
    abbName == "PIT" ~ "Pittsburgh Pirates",
    abbName == "STL" ~ "St. Louis Cardinals",
    abbName == "SFG" ~ "San Francisco Giants",
    abbName == "SDP" ~ "San Diego Padres",
  )) %>%
  select(team_name, poff_chance)

# get today' schedule
todays_games <-
  mlb_schedule(season = 2023) %>%
  filter(date == Sys.Date()) %>%
  select(contains("team_name"))

# get playoff odds from baseball-reference
playoff_url <- read_html("https://www.baseball-reference.com/leagues/majors/2023-playoff-odds.shtml")

poff_chances_bbref <-
  playoff_url %>%
  html_elements("table") %>%
  pluck(2) %>%
  html_table() %>%
  select(team_name = 2, poff_chance = 20) %>%
  mutate(poff_chance = as.numeric(str_extract(poff_chance, "[:digit:]*\\.[:digit:]"))) %>%
  replace_na(list(poff_chance = 0)) |> # some teams aren't numeric because bbref lists them as "<0.1%"
  filter(!str_detect(team_name, "Tm|East|Central|West") & team_name != "")

# get playoff odds from clay davenport's forecast site
playoff_davenport <- read_html("http://www.claydavenport.com/stats/ps_oddspec.html") %>%
  html_elements("pre") %>%
  html_text2() %>%
  str_split("\n")

# the above returns a list of data frames. iterate through them and pull out the information
playoff_chances_davenport <-
  playoff_davenport %>%
  map_df(function(x) {
    pluck(x) %>%
      as_tibble() %>%
      filter(row_number() > 3) %>%
      separate(value, c("one", "two", "three", "four", "five", "six", "seven", "eight", "nine"), sep = "\\s{2,}") %>%
      filter(one != "") %>%
      select(team_name = one, poff_chance = nine) %>%
      mutate(poff_chance = as.numeric(poff_chance)) %>%
      filter(!is.na(poff_chance))
  }) %>%
  mutate(
    team_name = case_when(
      str_detect(team_name, "Dodgers") ~ "Los Angeles Dodgers",
      str_detect(team_name, "Yankees") ~ "New York Yankees",
      str_detect(team_name, "Orioles") ~ "Baltimore Orioles",
      str_detect(team_name, "Red Sox") ~ "Boston Red Sox",
      str_detect(team_name, "Blue Jays") ~ "Toronto Blue Jays",
      str_detect(team_name, "Rays") ~ "Tampa Bay Rays",
      str_detect(team_name, "Guardians") ~ "Cleveland Guardians",
      str_detect(team_name, "Twins") ~ "Minnesota Twins",
      str_detect(team_name, "White Sox") ~ "Chicago White Sox",
      str_detect(team_name, "Tigers") ~ "Detroit Tigers",
      str_detect(team_name, "Royals") ~ "Kansas City Royals",
      str_detect(team_name, "Astros") ~ "Houston Astros",
      str_detect(team_name, "Angels") ~ "Los Angeles Angels",
      str_detect(team_name, "Athletics") ~ "Oakland Athletics",
      str_detect(team_name, "Mariners") ~ "Seattle Mariners",
      str_detect(team_name, "Nationals") ~ "Washington Nationals",
      str_detect(team_name, "Marlins") ~ "Miami Marlins",
      str_detect(team_name, "Mets") ~ "New York Mets",
      str_detect(team_name, "Phillies") ~ "Philadelphia Phillies",
      str_detect(team_name, "Cubs") ~ "Chicago Cubs",
      str_detect(team_name, "Pirates") ~ "Pittsburgh Pirates",
      str_detect(team_name, "Brewers") ~ "Milwaukee Brewers",
      str_detect(team_name, "Reds") ~ "Cincinnati Reds",
      str_detect(team_name, "Rangers") ~ "Texas Rangers",
      str_detect(team_name, "Padres") ~ "San Diego Padres",
      str_detect(team_name, "Giants") ~ "San Francisco Giants",
      str_detect(team_name, "Cardinals") ~ "St. Louis Cardinals",
      str_detect(team_name, "Rockies") ~ "Colorado Rockies",
      str_detect(team_name, "Braves") ~ "Atlanta Braves",
      str_detect(team_name, "Diamondbacks") ~ "Arizona Diamondbacks",
      TRUE ~ NA_character_
    )
  )


poff_chances <-
  poff_chances_bbref |>
  inner_join(playoff_chances_davenport, by = "team_name", suffix = c("_bbref", "_davenport")) %>%
  inner_join(poff_chances_fg, by = "team_name") |>
  select(team_name, poff_chance_bbref, poff_chance_davenport, poff_chance_fg = poff_chance) %>%
  inner_join(poff_chance_numberfire, by = "team_name") %>%
  select(team_name, poff_chance_bbref, poff_chance_davenport, poff_chance_fg, poff_chance_numberfire = poff_chance) %>%
  inner_join(poff_chance_teamrankings, by = "team_name") %>%
  select(team_name, poff_chance_bbref, poff_chance_davenport, poff_chance_fg, poff_chance_numberfire, poff_chance_teamrankings = poff_chance) %>%
  inner_join(poff_chance_pecota, by = "team_name") %>%
  select(team_name, poff_chance_bbref, poff_chance_davenport, poff_chance_fg, poff_chance_numberfire, poff_chance_teamrankings, poff_chance_pecota = poff_chance) %>%
  pivot_longer(-team_name, names_to = "site", values_to = "poff_chance")

poff_chances_today <-
  poff_chances %>%
  group_by(team_name) %>%
  summarize(median_poff_chance = round(median(poff_chance), 1)) %>%
  mutate(
    # compute 'interest' based off playoff chances. teams closer to 50% should be more interesting, and higher scores should be more interessting
    interest = 50 - abs(50 - median_poff_chance)
  )

twitter_handles <-
  poff_chances %>%
  distinct(team_name) %>%
  mutate(handle = case_when(
    team_name == "Baltimore Orioles" ~ "@Orioles",
    team_name == "Boston Red Sox" ~ "@RedSox",
    team_name == "Chicago White Sox" ~ "@WhiteSox",
    team_name == "Cleveland Guardians" ~ "@CleGuardians",
    team_name == "Detroit Tigers" ~ "@Tigers",
    team_name == "Houston Astros" ~ "@Astros",
    team_name == "Kansas City Royals" ~ "@Royals",
    team_name == "Los Angeles Angels" ~ "@Angels",
    team_name == "Minnesota Twins" ~ "@Twins",
    team_name == "New York Yankees" ~ "@Yankees",
    team_name == "Oakland Athletics" ~ "@Athletics",
    team_name == "Seattle Mariners" ~ "@Mariners",
    team_name == "Tampa Bay Rays" ~ "@RaysBaseball",
    team_name == "Texas Rangers" ~ "@Rangers",
    team_name == "Toronto Blue Jays" ~ "@BlueJays",
    team_name == "Arizona Diamondbacks" ~ "@Dbacks",
    team_name == "Atlanta Braves" ~ "@Braves",
    team_name == "Chicago Cubs" ~ "@Cubs",
    team_name == "Cincinnati Reds" ~ "@Reds",
    team_name == "Colorado Rockies" ~ "@Rockies",
    team_name == "Los Angeles Dodgers" ~ "@Dodgers",
    team_name == "Miami Marlins" ~ "@Marlins",
    team_name == "Milwaukee Brewers" ~ "@Brewers",
    team_name == "New York Mets" ~ "@Mets",
    team_name == "Philadelphia Phillies" ~ "@Phillies",
    team_name == "Pittsburgh Pirates" ~ "@Pirates",
    team_name == "San Diego Padres" ~ "@Padres",
    team_name == "San Francisco Giants" ~ "@SFGiants",
    team_name == "St. Louis Cardinals" ~ "@Cardinals",
    team_name == "Washington Nationals" ~ "@Nationals",
  ))


sched <-
  todays_games %>%
  inner_join(poff_chances_today, by = c("teams_away_team_name" = "team_name")) %>%
  select(contains("team"), poff_chance_away = median_poff_chance, interest_away = interest) %>%
  inner_join(poff_chances_today, by = c("teams_home_team_name" = "team_name")) %>%
  select(contains("team"), poff_chance_away, interest_away, poff_chance_home = median_poff_chance, interest_home = interest) %>%
  mutate(
    interest_game = interest_away + interest_home, # simple addition suggested by https://www.reddit.com/user/daedeloth86/
    interest_plus = round(interest_game / mean(interest_game) * 100, 0),
  ) %>%
  arrange(desc(interest_plus)) %>%
  select(teams_away_team_name, teams_home_team_name, interest_plus, interest_game, everything())

sched

# minimum interest score (most interesting) = 0
# maximum = 50


# take the current playoff chances, add the date, bind all the rows from the existing disk file, then save the new combined/appended file


poff_chances_clean <-
  poff_chances %>%
  mutate(
    site = case_when(
      site == "poff_chance_bbref" ~ "Baseball Reference",
      site == "poff_chance_davenport" ~ "Clay Davenport",
      site == "poff_chance_fg" ~ "FanGraphs",
      site == "poff_chance_numberfire" ~ "numberFire",
      site == "poff_chance_teamrankings" ~ "TeamRankings.com",
      site == "poff_chance_pecota" ~ "Baseball Prospectus (PECOTA)",
      site == "poff_chance_espn" ~ "ESPN",
    ),
    division = case_when(
      str_detect(team_name, "Orioles|Red Sox|Yankees|Blue Jays|Rays") ~ "AL East",
      str_detect(team_name, "White Sox|Twins|Tigers|Royals|Guardians") ~ "AL Central",
      str_detect(team_name, "Astros|Athletics|Angels|Rangers|Mariners") ~ "AL West",
      str_detect(team_name, "Mets|Phillies|Marlins|Braves|Nationals") ~ "NL East",
      str_detect(team_name, "Pirates|Reds|Brewers|Cardinals|Cubs") ~ "NL Central",
      str_detect(team_name, "Dodgers|Padres|Rockies|Diamondbacks|Giants") ~ "NL West"
    ),
    league = if_else(str_detect(division, "AL"), "American League", "National League")
  ) %>%
  group_by(team_name) %>%
  mutate(median_poff_chance = median(poff_chance)) %>%
  ungroup()

poff_chances_clean |>
  ggplot(aes(x = reorder(team_name, median_poff_chance), y = poff_chance)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(aes(color = site), size = 0.5) +
  coord_flip() +
  labs(y = "Playoff Chance (%)", x = "") +
  geom_hline(yintercept = 50, lty = "dashed") +
  facet_wrap(vars(league), scales = "free_y") +
  ggtitle("MLB Team Playoff Chances", subtitle = glue("Prior to Games Played on {Sys.Date()}"))


ggsave("playoff_chances.png")

# append data to disk
poff_chances_clean |>
  mutate(prediction_date = Sys.Date()) |>
  select(prediction_date, everything(), -median_poff_chance) |>
  write_csv(file = "playoff_chances.csv", append = TRUE)
```

# compute playoff chances change between April 22nd and the current date

```{r}
poff_chance_change <-
  read_csv("playoff_chances.csv") |>
  group_by(team_name, prediction_date) |>
  summarize(median_poff_chance = median(poff_chance)) |>
  filter(prediction_date == min(prediction_date) | prediction_date == max(prediction_date)) |>
  mutate(prediction_date = if_else(prediction_date == min(prediction_date), "start", "current")) |>
  pivot_wider(names_from = prediction_date, values_from = median_poff_chance) |>
  mutate(change = current - start) |>
  arrange(desc(change))

poff_chance_change |>
  mutate(abbrev = case_when(
    str_detect(team_name, "Giants") ~ "SFG",
    str_detect(team_name, "Red Sox") ~ "BOS",
    str_detect(team_name, "Pirates") ~ "PIT",
    str_detect(team_name, "Padres") ~ "SDP",
    str_detect(team_name, "Orioles") ~ "BAL",
    str_detect(team_name, "Dodgers") ~ "LAD",
    str_detect(team_name, "Diamondbacks") ~ "ARI",
    str_detect(team_name, "Twins") ~ "MIN",
    str_detect(team_name, "Rays") ~ "TBR",
    str_detect(team_name, "Angels") ~ "LAA",
    str_detect(team_name, "Giants") ~ "SFG",
    str_detect(team_name, "Braves") ~ "ATL",
    str_detect(team_name, "Rangers") ~ "TEX",
    str_detect(team_name, "Tigers") ~ "DET",
    str_detect(team_name, "Reds") ~ "CIN",
    str_detect(team_name, "Rockies") ~ "COL",
    str_detect(team_name, "Nationals") ~ "WAS",
    str_detect(team_name, "Athletics") ~ "OAK",
    str_detect(team_name, "Royals") ~ "KCR",
    str_detect(team_name, "Cubs") ~ "CHC",
    str_detect(team_name, "Astros") ~ "HOU",
    str_detect(team_name, "Phillies") ~ "PHI",
    str_detect(team_name, "Blue Jays") ~ "TOR",
    str_detect(team_name, "Mariners") ~ "SEA",
    str_detect(team_name, "Marlins") ~ "MIA",
    str_detect(team_name, "White Sox") ~ "CHW",
    str_detect(team_name, "Brewers") ~ "MIL",
    str_detect(team_name, "Guardians") ~ "CLE",
    str_detect(team_name, "Yankees") ~ "NYY",
    str_detect(team_name, "Mets") ~ "NYM",
    str_detect(team_name, "Cardinals") ~ "STL",
    TRUE ~ NA_character_
  )) |>
  ggplot(aes(change, current)) +
  geom_label_repel(aes(label = abbrev), max.overlaps = 20) +
  geom_point() +
  ggtitle("Playoff Chances & Changes",
    subtitle = glue("From 2023-04-22 to {Sys.Date()}")
  ) +
  labs(
    x = "Change Since April 22nd (percentage points)", y = "Current Playoff Chance (%)",
    caption = "Playoff chances: median of FG, B-Ref, BPro, Clay Davenport, Numberfire, TeamRankings"
  ) +
  geom_hline(yintercept = 50, lty = "dashed", color = "gray") +
  geom_vline(xintercept = 0, lty = "dashed", color = "gray")
#+ xlim(-55, 55) # TODO: figure out boundaries by taking the max & min change values and making those even somehwo

ggsave("playoff-change-change.png")
```



# make tweet

```{r}
# TODO: make twitter handles for each team via mutate,

tweet_data <-
  sched %>%
  filter(row_number() == 1) %>%
  inner_join(twitter_handles, by = c("teams_away_team_name" = "team_name")) %>%
  select(everything(), away_handle = handle) %>%
  inner_join(twitter_handles, by = c("teams_home_team_name" = "team_name")) %>%
  select(everything(), home_handle = handle)


away <- tweet_data$teams_away_team_name
away_pct <- tweet_data$poff_chance_away
away_handle <- tweet_data$away_handle

home <- tweet_data$teams_home_team_name
home_pct <- tweet_data$poff_chance_home
home_handle <- tweet_data$home_handle

interest <- tweet_data$interest_game
interest_plus <- tweet_data$interest_plus

playoff_start <- "2023-10-07"

tweet <- glue("Good morning! The @MLB playoffs start in {difftime(playoff_start, Sys.Date(), units = 'days') %>% floor() %>% as.numeric()} days. The current playoff picture is attached.

Most impactful game today: {away_handle} ({away_pct %>% round(0)}% chance) at {home_handle} ({home_pct %>% round(0)}%).

Srcs: @fangraphs @baseball_ref @baseballpro Clay Davenport @ESPN @numberFire @teamRankings")

tweet
nchar(tweet)
```
```{r}
sched %>%
  select(Visitor = teams_away_team_name, `Visitor Playoff Chance (%)` = poff_chance_away, `Home Team` = teams_home_team_name, `Home Team Playoff Chance (%)` = poff_chance_home, Interest = interest_game, `Interest+` = interest_plus) %>%
  mutate(across(where(is.numeric), ~ round(.x, 0))) %>%
  kbl(align = "c") %>%
  kable_classic()
```

tweet form:

"Full list of matchups & playoff chances. Chances closer to 50% are more interesting
Orioles (15%) at Rays (48%)
Brewers (64%) at Cardinals (77%)
Guardians (62%) at Blue Jays (85%)
Twins (48%) at Angels (0%)
Tigers(0%) at White Sox (42%)

```{r}
foo <-
  mlb_schedule(season = 2023) %>%
  filter(date == Sys.Date()) |>
  mutate(
    game_start = as_datetime(game_date, tz = "US/Eastern"),
    start_hour = hour(game_start)
  ) |>
  select(contains("team_name"), game_start, start_hour)

first_hour_start <- foo |>
  filter(row_number() == 1) |>
  pull(start_hour)

foo |>
  mutate(
    hrs_from_start = start_hour - first_hour_start,
    mod = start_hour - first_hour_start %% 2,
    chunk = case_when(
      hrs_from_start < 2 ~ "One",
      hrs_from_start < 4 ~ "Two",
      hrs_from_start < 6 ~ "Three",
      hrs_from_start < 8 ~ "Four",
      hrs_from_start < 10 ~ "Five",
      hrs_from_start < 12 ~ "Six"
    )
  )


# goal is to separate out chunks of games starting more than 2 hours apart

# |>
#   mutate(start_class = case_when(
#     start_hour < 12 ~ "Morning",
#     between(start_hour, 12, 16) ~ "Afternoon",
#     between(start_hour, 17, 19) ~ "Evening",
#     start_hour > 19 ~ "Night"
#   ))
```

```{r}
read_html("https://ans.mlb.com/b/ss/mlbglobal08,mlbcom08/1/H.27.4/s7244009547094?AQB=1&ndh=1&t=13%2F3%2F2023%2018%3A50%3A49%204%20300&mid=90337289130997972743705511536346669406&ce=UTF-8&ns=mlb&pageName=Baseballsavant.com%20Site%3A%20Statcast%20Expected%20wOBA%2C%20xBA%2C%20xSLG&g=https%3A%2F%2Fbaseballsavant.mlb.com%2Fleaderboard%2Fexpected_statistics%3Ftype%3Dpitcher&r=https%3A%2F%2Fbaseballsavant.mlb.com%2Fleaderboard%2Fstatcast%3Ftype%3Dpitcher&cc=USD&ch=Baseballsavant.com%20Site&events=event4&c1=Baseballsavant.com%20Site&c24=mlbglobal08%2Cmlbcom08&c35=4%2F13%2F2023%2019%3A50%3A49&c64=D%3Ds_vi&v64=D%3Ds_vi&s=1680x1050&c=24&j=1.6&v=N&k=Y&bw=1563&bh=554&p=PDF%20Viewer%3BChrome%20PDF%20Viewer%3BChromium%20PDF%20Viewer%3BMicrosoft%20Edge%20PDF%20Viewer%3BWebKit%20built-in%20PDF%3B&AQE=1")
```



```{r}
# bot <- rtweet_app()
# auth_as(bot)
#
# post_tweet(status="testing")
```
