services:
  - type: web
    name: mcfarland-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: MCFARLAND_DATA_URL
        sync: false
      - key: MCFARLAND_CORS_ORIGIN
        sync: false
  - type: web
    name: mcfarland-web
    env: node
    rootDir: web
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: NEXT_PUBLIC_API_BASE_URL
        fromService:
          type: web
          name: mcfarland-api
          property: url
      - key: NODE_VERSION
        value: 20
