
### Get league K and ISO rates for each season 

```{r}
#get league K rates for each season
league_rates <- fg_data %>%
  group_by(Season) %>%
  summarize(lg_K = sum(SO) / sum(PA) * 100,
            lg_ISO = (sum(Doubles) + (2 * sum(Triples)) + (3 * sum(HR))) / sum(AB))
```

### Calculate relative changes in K and ISO rates for teams from 2010-2016.

```{r}
k_iso_rate_team_changes <- fg_team_data %>%
  select(Season, Team, PA, SO, Doubles, Triples, HR, AB) %>%
  group_by(Team, Season) %>%
  arrange(Team, Season) %>%
  summarize(team_k_rate = sum(SO) / sum(PA) * 100,
            team_ISO = (Doubles + (2 * Triples) + (3 * HR)) / AB) %>%
  inner_join(k_rate_per_season, by="Season") %>%
  mutate(k_minus = round(team_k_rate / lg_K * 100, 0),
         k_rate_increase_from_prev_yr = k_minus - lag(k_minus),
         ISO_minus = round(team_ISO / lg_ISO * 100, 0),
         iso_increase_from_prev_yr = ISO_minus - lag(ISO_minus))

#plot all teams' changes
p <- ggplot(data=k_rate_team_changes, aes(x=Season, y=k_minus, color=Team)) + geom_line() + geom_point() +
  ggtitle("Relative strikeout rates for non-pitchers, 2010-2016") + labs(y="Relative K rate (100 = Lg. Avg.)")
gg <- ggplotly(p)

```



### Make all CSV files needed for graphs and tables

```{r}

#royals relative K rates since 2010
royals_k_rate <- k_iso_rate_team_changes %>%
  filter(Team == "Royals") %>%
  ungroup %>%
  select(Season, k_minus) %>%
  write_csv("royals-k-rate-changes.csv")



#K rate changes 2015-2016
team_k_rate_changes_2016 <- k_iso_rate_team_changes %>%
  filter(Season == "2016") %>%
  arrange(desc(k_rate_increase_from_prev_yr)) %>%
  select(Team, k_rate_increase_from_prev_yr) %>%
  write_csv("2016-k-rate-increases.csv")

top_10_k_increases_since_2010 <- k_iso_rate_team_changes %>%
  arrange(desc(k_rate_increase_from_prev_yr)) %>%
  select(Team, Season, k_rate_increase_from_prev_yr) %>%
  write_csv("top-10-k-rate-increases.csv")
  
team_iso_changes_2016 <- k_iso_rate_team_changes %>%
  filter(Season == 2016) %>%
  select(Team, iso_increase_from_prev_yr) %>%
  arrange(desc(iso_increase_from_prev_yr)) %>%
  write_csv("iso_increase_in_2016.csv")


```



```{r}




k_bb_rate_changers_players <- fg_data %>%
  select(Name, Season, Team, PA, K_p, BB_p, ISO) %>%
  group_by(Season) %>%
  mutate(lg_K = mean(K_p), #compute league averages to normalize league changes in K and BB rates 
         lg_BB = mean(BB_p)) %>%
  filter(PA > 100) %>% #remove seasons shortened due to injury or whatever
  group_by(Name) %>%
  arrange(Name, Season) %>%
  mutate(K_minus = round((K_p / lg_K) * 100, 0),
         BB_minus = round((BB_p / lg_BB) * 100, 0),
         K_perc_change = K_minus - lag(K_minus),
         BB_perc_change = BB_minus - lag(BB_minus),
         overall_change = BB_perc_change - K_perc_change) %>%
  filter(Season == 2016, is.na(K_perc_change) == FALSE, is.finite(K_perc_change) == TRUE)


k_bb_decliners <- k_bb_rate_changers_players %>%
  filter(K_perc_change > 0, BB_perc_change < 0)

k_bb_boosters <- k_bb_rate_changers_players %>%
  filter(K_perc_change < 0, BB_perc_change > 0)

```

## Find GB rate changers among 2016 players with at least 100 PA in back-to-back seasons

```{r}
gb_rate_changers_players <- fg_data %>%
  select(Name, Season, Team, PA, GB_p, ISO) %>%
  group_by(Season) %>%
  mutate(lg_GB = mean(GB_p)) %>% #compute league averages to normalize league changes in stats we care about 
  filter(PA > 100) %>% #remove seasons shortened due to injury or whatever
  group_by(Name) %>%
  arrange(Name, Season) %>%
  mutate(GB_minus = round((GB_p / lg_GB) * 100, 0),
         GB_perc_change = GB_minus - lag(GB_minus)) %>%
  filter(Season == 2016, is.na(GB_perc_change) == FALSE, is.finite(GB_perc_change) == TRUE)
  
gb_rate_changers_teams <- gb_rate_changers_players %>%
  group_by(Team) %>%
  summarize(num_players = n(),
            mean_gb_rate_change = round(mean(GB_perc_change), 2))

```