---
title: "baseball-savant-scraper"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
install.packages("rvest")
library(XML)
library(rvest)
```

## R Markdown


```{r}

url <- "https://baseballsavant.mlb.com/statcast_search?hfPT=&hfZ=&hfGT=R%7C&hfPR=&hfAB=&stadium=&hfBBT=&hfBBL=&hfC=&season=2016&player_type=pitcher&hfOuts=&pitcher_throws=&batter_stands=&start_speed_gt=&start_speed_lt=&perceived_speed_gt=&perceived_speed_lt=&spin_rate_gt=&spin_rate_lt=&exit_velocity_gt=&exit_velocity_lt=&launch_angle_gt=&launch_angle_lt=&distance_gt=&distance_lt=&batted_ball_angle_gt=&batted_ball_angle_lt=&game_date_gt=&game_date_lt=&team=&position=&hfRO=&home_road=&hfInn=&min_pitches=0&min_results=0&group_by=name&sort_col=pitches&player_event_sort=start_speed&sort_order=desc&min_abs=0&xba_gt=&xba_lt=&px1=&px2=&pz1=&pz2=&ss_gt=&ss_lt=#results"

#results are in: <table id="search_results">

statcast <- read_html(url) %>%
  html_nodes(xpath = "//*[@id='search_results']") %>%
  html_table(fill=TRUE)


#going to need R selenium to:
#expand each row of the table.
#download each sub-table as a CSV. xpath of CSV button: //*[@id="csv_name_434378_"]/img
#pull into R
#combine into one bigass data frame


//*[@id="details_div_name_434378_"]/table
