---
title: "FanGraphs Leaderboard Scraper"
output: html_document
---

### Load required packages

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(magrittr)
library(XML)
library(plotly)
library(readr)
```

### Create lookup table

The user will pass named strings into scrape_player_batting_data(). These strings need to be transformed into numbers for use in the leaderboards URL.

```{r}
dashboards <- as.character(c("standard", "advanced", "batted_ball", "win_probability", "pitch_type",
                             "plate_discipline", "value", "pitch_value", "pfx_pitch_type", "pfx_velocity", 
                             "pfx_h_mov", "pfx_v_mov", "pfx_pitch_val","pfx_pitch_val_c", "pfx_plate_discipline"))
types <- c(0, 1, 2, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 15)
leaderboard_lookup <- data.frame(dashboards, types)
```

### Clean up data  
  
Clean up a number of inconsistencies associated with leaderboards data elements that prevent useful analysis in R.
  
```{r}    
clean_data <- function(df){
  df <- df[, !duplicated(colnames(df))] #Remove duplicate columns, like 'PA' which is returned from multiple dashboards
  df %<>%
    select(-matches("#")) #remove the 'Rank' column from the data

  #Handle percentage columns, which reports rates as strings
  for(i in names(df)){
    if(is.na(grep("%", i, value = TRUE)[1]) == FALSE | i == "HR/FB"){
      df[[i]] <- as.numeric(sub("%", "", df[[i]]))/100
    }
  }
  
  #Handle the "Dollars" column, which reports negative values in parentheses and has a $ character
  if ("Dollars" %in% names(df)){
    #Convert values in parentheses to strings with "-"" in front 
    df$Dollars <- gsub("\\(", "-", df$Dollars)
    df$Dollars <- gsub("\\)", "", df$Dollars)
    
    #Remove dollar sign & convert to numeric
    df$Dollars <- as.numeric(sub("\\$", "", df$Dollars))
  }
  
  #Convert every column except Name and Team to numeric. Otherwise they are characters & don't sort properly
  cols_to_convert <- c(1, 4:ncol(df))
  df[,cols_to_convert] %<>%
    lapply(function(x) as.numeric(x))
  
  #Make a few column names R-friendly
  colnames(df) <- gsub("\\/", "_per_", colnames(df))
  colnames(df) <- gsub("%", "_p", colnames(df))
  colnames(df) <- gsub("\\+", "_plus", colnames(df))
  colnames(df)[8] <- "Singles"
  colnames(df)[9] <- "Doubles"
  colnames(df)[10] <- "Triples"


  return(df)
}
```


### Scrape data

```{r}
scrape_player_batting_data <- function(n, start_season, end_season){
  
  #Get type IDs of dashboard(s) the user wants
  if("all" %in% n){
    types <- leaderboard_lookup$types
  }
  else{
    n <- as.data.frame(n)
    colnames(n)[1] <- "dashboards"
    n <- inner_join(leaderboard_lookup, n, by="dashboards")
    types <- n$types
  }
  
  #Compute number of players to grab per dashboard; assume 900 non-pitchers per season
  num_players <- 900 * (end_season - start_season + 1)

  #Combine requested dashboards into one data frame
  df <- plyr::join_all(
    sapply(types, function(x){
      url <- sprintf("http://www.fangraphs.com/leaders.aspx?pos=np&stats=bat&lg=all&qual=0&type=%s&season=%s&month=0&season1=%s&ind=1&team=0&rost=0&age=0&filter=&players=0&page=1_%s", x, end_season, start_season, num_players)
      out <- readHTMLTable(url, stringsAsFactors = FALSE)
      out <- as.data.frame(out$LeaderBoard1_dg1_ctl00)
      }
      ),
    by=c("Name", "Team", "Season")
  )
  
  df <- clean_data(df)
  return(df)
}
  #Clean up data
```
  


### In progress

```{r}
compute_yoy_change <- function(df, stat){
  new_column = sprintf("%s_perc_change", stat)
  new_df <- df %>%
    select_(Name, Season, Team, PA, stat, wOBA) %>%
    filter(PA > 100) %>% #remove seasons shortened due to injury or whatever
    group_by(Name) %>%
    arrange(Name, Season) %>%
    mutate(new_column = round(((stat - lag(stat)) / lag(stat)) * 100, 2)) %>%
    filter(Season == 2016, is.na(new_column) == FALSE, is.finite(new_column) == TRUE) %>% #focus on current year; ignore rookies
    arrange(desc(new_column))
  
  return(new_df)
}

```

### Get Data

```{r}
fg_data <- scrape_player_batting_data("all", 2016, 2016)
fg_team_data <- read_csv("~/Downloads/fg-team-data.csv")
colnames(fg_team_data)[7] <- "Singles"
colnames(fg_team_data)[8] <- "Doubles"
colnames(fg_team_data)[9] <- "Triples"
colnames(fg_team_data)[1] <- "Season"



```

