name: Daily Baseball Data Refresh

on:
  schedule:
    - cron: '0 11 * * *'  # 6 AM EST (11 AM UTC)
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3'

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            tidyverse
            baseballr
            stringi

      - name: Refresh baseball data
        run: Rscript refresh_data.R

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add full_stats_hitters.csv player_names_hitters.csv
          git diff --staged --quiet || git commit -m "Daily data refresh $(date)"
          git pull --rebase origin master
          git push origin master
