name: Daily Baseball Data Refresh
on:
  schedule:
    - cron: '0 11 * * *'  # 6 AM EST (11 AM UTC) - fixed the cron syntax
  workflow_dispatch:  # Allows manual trigger

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3'
          
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            tidyverse
            baseballr
            stringi
            httr
            jsonlite
            janitor
            
      - name: Refresh baseball data
        run: Rscript refresh_data.R
        
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add the new file names that the updated script creates
          git add full_stats_hitters.csv full_stats_pitchers.csv player_lookup.csv
          
          # Remove old files if they exist (cleanup)
          git rm -f full_stats.csv player_names.csv || true
          
          # Commit if there are changes
          git diff --staged --quiet || git commit -m "Daily data refresh $(date)"
          git push
